import { test } from "node:test";
import assert from "node:assert/strict";
import {
  stripQuotedReply,
  decodeBase64Url,
  encodeMimeHeader,
  extractAddress,
  extractDisplayName,
  isAutoGenerated,
  isNoReplyAddress,
  replySubject,
  decodeRfc2047,
  resolveMailbox,
} from "../src/emailText.js";
import { sanitizeEmailReply } from "../src/format.js";

test("stripQuotedReply: remove bloco 'Em ... escreveu:' e linhas citadas", () => {
  const body = [
    "Perfeito, quero reservar para sexta.",
    "",
    "Em sex., 10 de jul. de 2026, Aria · The World Keys escreveu:",
    "> Olá! Encontrei o restaurante que você pediu.",
    "> Sua reserva é feita direto na página dele.",
  ].join("\n");
  assert.equal(stripQuotedReply(body), "Perfeito, quero reservar para sexta.");
});

test("stripQuotedReply: remove cabeçalho citado From/De + Sent/Enviado", () => {
  const body = [
    "Obrigado! Pode ser às 20h.",
    "",
    "De: Aria · The World Keys <reservation@theworldkeys.com>",
    "Enviado: sexta-feira, 10 de julho de 2026 14:03",
    "Para: cliente@gmail.com",
    "Assunto: Re: Reserva",
    "Texto antigo aqui.",
  ].join("\n");
  assert.equal(stripQuotedReply(body), "Obrigado! Pode ser às 20h.");
});

test("stripQuotedReply: email sem citação passa intacto", () => {
  const body = "Olá, vocês têm restaurante japonês em Paris?\nDe preferência algo intimista.";
  assert.equal(stripQuotedReply(body), body);
});

test("decodeBase64Url: decodifica payload do Gmail (base64url sem padding)", () => {
  const original = "Olá, TWK! ✓";
  const b64url = Buffer.from(original, "utf8")
    .toString("base64")
    .replace(/\+/g, "-")
    .replace(/\//g, "_")
    .replace(/=+$/, "");
  assert.equal(decodeBase64Url(b64url).toString("utf8"), original);
});

test("encodeMimeHeader: ASCII passa direto, acentos viram RFC 2047", () => {
  assert.equal(encodeMimeHeader("Re: Booking"), "Re: Booking");
  const encoded = encodeMimeHeader("Reserva confirmada — São Paulo");
  assert.ok(encoded.startsWith("=?UTF-8?B?") && encoded.endsWith("?="));
});

test("extractAddress/extractDisplayName: 'Nome <a@b.com>' e endereço puro", () => {
  assert.equal(extractAddress('"Maria Silva" <Maria.Silva@Gmail.com>'), "maria.silva@gmail.com");
  assert.equal(extractAddress("cliente@empresa.com"), "cliente@empresa.com");
  assert.equal(extractDisplayName('"Maria Silva" <m@g.com>'), "Maria Silva");
  assert.equal(extractDisplayName("m@g.com"), null);
});

test("isAutoGenerated: detecta auto-reply e listas", () => {
  assert.ok(isAutoGenerated({ "auto-submitted": "auto-replied" }));
  assert.ok(isAutoGenerated({ precedence: "bulk" }));
  assert.ok(isAutoGenerated({ "list-unsubscribe": "<mailto:x@y.com>" }));
  assert.ok(!isAutoGenerated({ "auto-submitted": "no" }));
  assert.ok(!isAutoGenerated({}));
});

test("isNoReplyAddress: no-reply, mailer-daemon e variantes", () => {
  assert.ok(isNoReplyAddress("no-reply@empresa.com"));
  assert.ok(isNoReplyAddress("noreply@empresa.com"));
  assert.ok(isNoReplyAddress("mailer-daemon@googlemail.com"));
  assert.ok(!isNoReplyAddress("maria.reply@gmail.com"));
  assert.ok(!isNoReplyAddress("cliente@empresa.com"));
});

test("replySubject: adiciona Re: sem empilhar", () => {
  assert.equal(replySubject("Reserva em Milão"), "Re: Reserva em Milão");
  assert.equal(replySubject("Re: Reserva em Milão"), "Re: Reserva em Milão");
  assert.equal(replySubject("RE: reserva"), "RE: reserva");
  assert.equal(replySubject(null), "Re: The World Keys");
});

test("sanitizeEmailReply: remove marcadores WhatsApp/markdown e emojis", () => {
  const raw = "Sua reserva *TWK-AB12* no _Le Bernardin_ está **confirmada**! 🎉";
  assert.equal(sanitizeEmailReply(raw), "Sua reserva TWK-AB12 no Le Bernardin está confirmada!");
});

test("sanitizeEmailReply: preserva underscores de URLs e identificadores", () => {
  const raw = "Acesse https://theworldkeys.com/h/le_bernardin_ny para reservar.";
  assert.equal(sanitizeEmailReply(raw), raw);
});

// ─── Modo n8n ─────────────────────────────────────────────────────────────────

import { htmlToText, normalizeInboundEmail, subjectLooksAutoReply } from "../src/emailText.js";

test("htmlToText: remove tags e decodifica entidades", () => {
  const t = htmlToText("<div><p>Ol&aacute;!</p><p>Quero uma <b>mesa</b> &amp; vinho.<br/>Hoje.</p></div>".replace("&aacute;", "á"));
  assert.equal(t, "Olá!\nQuero uma mesa & vinho.\nHoje.");
});

test("subjectLooksAutoReply: detecta férias/auto-reply multilíngue", () => {
  assert.ok(subjectLooksAutoReply("Automatic reply: Re: Reserva"));
  assert.ok(subjectLooksAutoReply("Resposta automática: ausência"));
  assert.ok(subjectLooksAutoReply("Out of Office"));
  assert.ok(!subjectLooksAutoReply("Re: Reserva em Milão"));
  assert.ok(!subjectLooksAutoReply(null));
});

test("normalizeInboundEmail: payload típico do n8n", () => {
  const m = normalizeInboundEmail({
    from: '"Marie Dubois" <Marie.Dubois@Gmail.com>',
    subject: "Reserva em Paris",
    text: "Bonjour!",
    html: "",
    messageId: "18c2f0aa9",
    threadId: "18c2f0aa9",
  });
  assert.ok(m);
  assert.equal(m.from, "marie.dubois@gmail.com");
  assert.equal(m.fromName, "Marie Dubois");
  assert.equal(m.messageId, "18c2f0aa9");
});

test("normalizeInboundEmail: tolera variações de campo e envelope body/array", () => {
  const m = normalizeInboundEmail([{ body: { From: "cliente@x.com", Subject: "Oi", textPlain: "olá", id: "abc123", thread_id: "t1" } }]);
  assert.ok(m);
  assert.equal(m.from, "cliente@x.com");
  assert.equal(m.subject, "Oi");
  assert.equal(m.text, "olá");
  assert.equal(m.messageId, "abc123");
  assert.equal(m.threadId, "t1");
});

test("normalizeInboundEmail: rejeita payload sem essenciais e filtra anexos inválidos", () => {
  assert.equal(normalizeInboundEmail({ subject: "sem from" }), null);
  assert.equal(normalizeInboundEmail("string"), null);
  const m = normalizeInboundEmail({
    from: "a@b.com", messageId: "1",
    attachments: [{ mimeType: "image/png", data: "AAAA" }, { filename: "sem-dados.png" }],
  });
  assert.ok(m);
  assert.equal(m.attachments.length, 1);
  assert.equal(m.attachments[0].mimeType, "image/png");
});

test("normalizeInboundEmail: carrega snippet e faz parse de payload string", () => {
  const m = normalizeInboundEmail({
    from: "costa.marlon08@gmail.com", id: "19f5c3f",
    text: "", html: "", snippet: "Preciso pagar para reservar?",
    payload: JSON.stringify({ mimeType: "multipart/alternative", parts: [] }),
  });
  assert.ok(m);
  assert.equal(m.snippet, "Preciso pagar para reservar?");
  assert.equal((m.payload as { mimeType: string }).mimeType, "multipart/alternative");
});

test("normalizeInboundEmail: aceita payload como objeto embutido", () => {
  const m = normalizeInboundEmail({
    from: "a@b.com", id: "1", payload: { mimeType: "text/plain" },
  });
  assert.ok(m);
  assert.equal((m.payload as { mimeType: string }).mimeType, "text/plain");
});

test("decodeRfc2047: decodifica encoded-words B e Q", () => {
  assert.equal(decodeRfc2047("=?UTF-8?B?Q2FzYSBkbyBQcmVnbw==?="), "Casa do Prego");
  assert.equal(decodeRfc2047("=?utf-8?q?Confirma=C3=A7=C3=A3o_de_reserva?="), "Confirmação de reserva");
  // Texto sem encoded-word passa intacto
  assert.equal(decodeRfc2047("Reserva para sábado"), "Reserva para sábado");
});

test("extractAddress: sobrevive a header n8n mangled (o bug do DMARC)", () => {
  // Header entregue SEM decodificar pelo n8n — era isso que derrotava a guarda
  // de no-reply e fazia o agente responder relatório DMARC gastando tokens.
  const mangled = "=?UTF-8?Q?noreply-dmarc-support@google.com?=";
  const addr = extractAddress(mangled);
  assert.equal(addr, "noreply-dmarc-support@google.com");
  assert.ok(isNoReplyAddress(addr!)); // agora a guarda pega
  // Forma com display name codificado + endereço angulado continua ok
  assert.equal(extractAddress('=?UTF-8?B?Q29kZVBlbg==?= <support@codepen.io>'), "support@codepen.io");
});

test("resolveMailbox: campo explícito → header To → fallback", () => {
  const own = ["support@theworldkeys.com", "reservation@theworldkeys.com"];
  // Campo explícito do fluxo n8n vence
  assert.equal(resolveMailbox("reservation@theworldkeys.com", null, own, "support@theworldkeys.com"), "reservation@theworldkeys.com");
  // Explícito desconhecido (typo no n8n) não passa — cai para o To
  assert.equal(
    resolveMailbox("errada@x.com", "The World Keys <reservation@theworldkeys.com>", own, "support@theworldkeys.com"),
    "reservation@theworldkeys.com",
  );
  // Sem explícito, acha a nossa caixa dentro do To
  assert.equal(
    resolveMailbox(null, "restaurante <luca@gmail.com>, reservation@theworldkeys.com", own, "support@theworldkeys.com"),
    "reservation@theworldkeys.com",
  );
  // Nada identificável → caixa principal
  assert.equal(resolveMailbox(null, null, own, "support@theworldkeys.com"), "support@theworldkeys.com");
});

test("normalizeInboundEmail: carrega mailbox e to (multi-caixa)", () => {
  const m = normalizeInboundEmail({
    from: "lucasrooftop@gmail.com",
    subject: "Re: Pending Request",
    text: "Can we move it to 8pm?",
    id: "luca1",
    mailbox: "Reservation@TheWorldKeys.com",
    to: "reservation@theworldkeys.com",
  });
  assert.ok(m);
  assert.equal(m.mailbox, "reservation@theworldkeys.com"); // normalizado p/ minúsculo
  assert.equal(m.to, "reservation@theworldkeys.com");
  // Sem os campos → null (o servidor cai no fallback)
  const m2 = normalizeInboundEmail({ from: "a@b.com", id: "1", text: "oi" });
  assert.ok(m2);
  assert.equal(m2.mailbox, null);
});

test("normalizeInboundEmail: decodifica From/Subject RFC 2047 do n8n", () => {
  const m = normalizeInboundEmail({
    from: "=?UTF-8?Q?noreply-dmarc-support@google.com?=",
    subject: "=?utf-8?q?Report_domain:_theworldkeys.com?=",
    text: "This is an aggregate report.",
    id: "dmarc1",
  });
  assert.ok(m);
  assert.equal(m.from, "noreply-dmarc-support@google.com");
  assert.equal(m.subject, "Report domain: theworldkeys.com");
});
