/**
 * campaignSeed.ts — histórico dos envios da campanha de fundadores.
 * GERADO a partir de orchestrator/state/envios-fundadores-2026-08.csv (fonte de verdade).
 * Inserido com ON CONFLICT (gmail_id) DO NOTHING — idempotente, nunca sobrescreve.
 */
export interface CampaignSeedRow {
  gmail_id: string; restaurant_id: string; restaurant_name: string;
  campaign: string; wave: string; touch_no: number;
  recipient: string; language: string; sent_at: string;
  status: string; note: string;
}
export const CAMPAIGN_SEED: CampaignSeedRow[] = [
 {
  "gmail_id": "1a02581e959616a8",
  "restaurant_id": "253542",
  "restaurant_name": "BOTECO BELMONTE",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "1-ENGAJADOS",
  "touch_no": 1,
  "recipient": "costa.marlon08@gmail.com",
  "language": "pt",
  "sent_at": "2026-08-21",
  "status": "enviado",
  "note": "contato oficial do catálogo"
 },
 {
  "gmail_id": "1a0259eaed40c55f",
  "restaurant_id": "253542",
  "restaurant_name": "BOTECO BELMONTE",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "1-ENGAJADOS",
  "touch_no": 1,
  "recipient": "lucaspeixotodacruz@gmail.com",
  "language": "pt",
  "sent_at": "2026-08-21",
  "status": "enviado",
  "note": "cópia idêntica a pedido do fundador"
 },
 {
  "gmail_id": "1a03f5e27ea294a0",
  "restaurant_id": "35219",
  "restaurant_name": "SRI TRAT",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "1-ENGAJADOS",
  "touch_no": 1,
  "recipient": "info@sritrat.com",
  "language": "en",
  "sent_at": "2026-08-26",
  "status": "enviado",
  "note": "lote Onda 1"
 },
 {
  "gmail_id": "1a03f5f32b3bc788",
  "restaurant_id": "255019",
  "restaurant_name": "MONAK",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "1-ENGAJADOS",
  "touch_no": 1,
  "recipient": "marcthao2014@gmail.com",
  "language": "fr",
  "sent_at": "2026-08-26",
  "status": "enviado",
  "note": "lote Onda 1"
 },
 {
  "gmail_id": "1a03f613bb01812a",
  "restaurant_id": "81583",
  "restaurant_name": "LE TOBSIL",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "1-ENGAJADOS",
  "touch_no": 1,
  "recipient": "restobsil@yahoo.fr",
  "language": "fr",
  "sent_at": "2026-08-26",
  "status": "enviado",
  "note": "lote Onda 1"
 },
 {
  "gmail_id": "1a03f6356fc04c77",
  "restaurant_id": "58502",
  "restaurant_name": "ATHÉNÉE",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "1-ENGAJADOS",
  "touch_no": 1,
  "recipient": "athenee@panasgroup.gr",
  "language": "en",
  "sent_at": "2026-08-26",
  "status": "enviado",
  "note": "lote Onda 1"
 },
 {
  "gmail_id": "1a03f6496f56bc8a",
  "restaurant_id": "79630",
  "restaurant_name": "LA ROUTE DU MIAM",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "1-ENGAJADOS",
  "touch_no": 1,
  "recipient": "laroutedumiam06@gmail.com",
  "language": "fr",
  "sent_at": "2026-08-26",
  "status": "enviado",
  "note": "lote Onda 1"
 },
 {
  "gmail_id": "1a03f65e1ccbe950",
  "restaurant_id": "76676",
  "restaurant_name": "WOO TENDER",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "1-ENGAJADOS",
  "touch_no": 1,
  "recipient": "wootender@gmail.com",
  "language": "en",
  "sent_at": "2026-08-26",
  "status": "enviado",
  "note": "lote Onda 1"
 },
 {
  "gmail_id": "1a03f6715930a17c",
  "restaurant_id": "306839",
  "restaurant_name": "THE REVOLVING",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "1-ENGAJADOS",
  "touch_no": 1,
  "recipient": "caign_info@hilton.com",
  "language": "en",
  "sent_at": "2026-08-26",
  "status": "enviado",
  "note": "lote Onda 1"
 },
 {
  "gmail_id": "1a03f68734578301",
  "restaurant_id": "18044",
  "restaurant_name": "Il Salumaio di Montenapoleone",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "1-ENGAJADOS",
  "touch_no": 1,
  "recipient": "info@ilsalumaiodimontenapoleone.it",
  "language": "it",
  "sent_at": "2026-08-26",
  "status": "enviado",
  "note": "lote Onda 1"
 },
 {
  "gmail_id": "1a03f69add6df37d",
  "restaurant_id": "20651",
  "restaurant_name": "LEI GARDEN",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "1-ENGAJADOS",
  "touch_no": 1,
  "recipient": "booking@leigardengroup.com",
  "language": "en",
  "sent_at": "2026-08-26",
  "status": "enviado",
  "note": "lote Onda 1"
 },
 {
  "gmail_id": "1a03f78394a6af30",
  "restaurant_id": "43298",
  "restaurant_name": "IL SANLORENZO",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "1-ENGAJADOS",
  "touch_no": 1,
  "recipient": "info@ilsanlorenzo.it",
  "language": "it",
  "sent_at": "2026-08-26",
  "status": "enviado",
  "note": "lote Onda 1 (reenvio pelo coordenador apos bloqueio transitorio)"
 },
 {
  "gmail_id": "1a03f6ed901d1be4",
  "restaurant_id": "16987",
  "restaurant_name": "ELEOS",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "1-ENGAJADOS",
  "touch_no": 1,
  "recipient": "beyoglueleos@hotmail.com",
  "language": "en",
  "sent_at": "2026-08-26",
  "status": "enviado",
  "note": "lote Onda 1"
 },
 {
  "gmail_id": "1a03f6fcc1ea702c",
  "restaurant_id": "35087",
  "restaurant_name": "EAT SIGHT STORY DECK",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "1-ENGAJADOS",
  "touch_no": 1,
  "recipient": "service@salaarun.com",
  "language": "en",
  "sent_at": "2026-08-26",
  "status": "enviado",
  "note": "lote Onda 1"
 },
 {
  "gmail_id": "1a03f792f1724d96",
  "restaurant_id": "254445",
  "restaurant_name": "LA BULLONA",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "1-ENGAJADOS",
  "touch_no": 1,
  "recipient": "info@bullona.com",
  "language": "it",
  "sent_at": "2026-08-26",
  "status": "enviado",
  "note": "lote Onda 1 (reenvio pelo coordenador apos bloqueio transitorio)"
 },
 {
  "gmail_id": "1a03f738d3eeaede",
  "restaurant_id": "298865",
  "restaurant_name": "Menina Sardinha",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "1-ENGAJADOS",
  "touch_no": 1,
  "recipient": "menina.sardinha@gmail.com",
  "language": "pt",
  "sent_at": "2026-08-26",
  "status": "enviado",
  "note": "lote Onda 1"
 },
 {
  "gmail_id": "1a03f747fb640081",
  "restaurant_id": "88557",
  "restaurant_name": "TIO PEPE",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "1-ENGAJADOS",
  "touch_no": 1,
  "recipient": "miguel@restaurantetiopepe.com",
  "language": "en",
  "sent_at": "2026-08-26",
  "status": "enviado",
  "note": "lote Onda 1"
 },
 {
  "gmail_id": "1a03f757979e1a13",
  "restaurant_id": "15385",
  "restaurant_name": "THE LOBSTER HOUSE",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "1-ENGAJADOS",
  "touch_no": 1,
  "recipient": "lobsterhouse@live.fr",
  "language": "fr",
  "sent_at": "2026-08-26",
  "status": "enviado",
  "note": "lote Onda 1"
 },
 {
  "gmail_id": "1a03f76693ed3934",
  "restaurant_id": "260033",
  "restaurant_name": "NAMMOS",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "1-ENGAJADOS",
  "touch_no": 1,
  "recipient": "Reservations@nammos.ae",
  "language": "en",
  "sent_at": "2026-08-26",
  "status": "enviado",
  "note": "lote Onda 1"
 },
 {
  "gmail_id": "1a048b9065433cdd",
  "restaurant_id": "35219",
  "restaurant_name": "SRI TRAT",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "TOQUE2-LOTE-A",
  "touch_no": 2,
  "recipient": "info@sritrat.com",
  "language": "en",
  "sent_at": "2026-08-28",
  "status": "enviado",
  "note": "toque 2"
 },
 {
  "gmail_id": "1a048b9c52ebaa18",
  "restaurant_id": "255019",
  "restaurant_name": "MONAK",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "TOQUE2-LOTE-A",
  "touch_no": 2,
  "recipient": "marcthao2014@gmail.com",
  "language": "fr",
  "sent_at": "2026-08-28",
  "status": "enviado",
  "note": "toque 2"
 },
 {
  "gmail_id": "1a048ba3cc786f63",
  "restaurant_id": "81583",
  "restaurant_name": "LE TOBSIL",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "TOQUE2-LOTE-A",
  "touch_no": 2,
  "recipient": "restobsil@yahoo.fr",
  "language": "fr",
  "sent_at": "2026-08-28",
  "status": "enviado",
  "note": "toque 2"
 },
 {
  "gmail_id": "1a048bb691dd3730",
  "restaurant_id": "58502",
  "restaurant_name": "ATHÉNÉE",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "TOQUE2-LOTE-A",
  "touch_no": 2,
  "recipient": "athenee@panasgroup.gr",
  "language": "en",
  "sent_at": "2026-08-28",
  "status": "enviado",
  "note": "toque 2"
 },
 {
  "gmail_id": "1a048bbff8259d5d",
  "restaurant_id": "79630",
  "restaurant_name": "LA ROUTE DU MIAM",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "TOQUE2-LOTE-A",
  "touch_no": 2,
  "recipient": "laroutedumiam06@gmail.com",
  "language": "fr",
  "sent_at": "2026-08-28",
  "status": "enviado",
  "note": "toque 2"
 },
 {
  "gmail_id": "1a048bc9428609a4",
  "restaurant_id": "76676",
  "restaurant_name": "WOO TENDER",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "TOQUE2-LOTE-A",
  "touch_no": 2,
  "recipient": "wootender@gmail.com",
  "language": "en",
  "sent_at": "2026-08-28",
  "status": "enviado",
  "note": "toque 2 (respondeu ao toque 1"
 },
 {
  "gmail_id": "1a048bda01183a6e",
  "restaurant_id": "306839",
  "restaurant_name": "THE REVOLVING",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "TOQUE2-LOTE-A",
  "touch_no": 2,
  "recipient": "caign_info@hilton.com",
  "language": "en",
  "sent_at": "2026-08-28",
  "status": "enviado",
  "note": "toque 2"
 },
 {
  "gmail_id": "1a048be429600fa0",
  "restaurant_id": "18044",
  "restaurant_name": "Il Salumaio di Montenapoleone",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "TOQUE2-LOTE-A",
  "touch_no": 2,
  "recipient": "info@ilsalumaiodimontenapoleone.it",
  "language": "it",
  "sent_at": "2026-08-28",
  "status": "enviado",
  "note": "toque 2"
 },
 {
  "gmail_id": "1a048bec7e018d90",
  "restaurant_id": "20651",
  "restaurant_name": "LEI GARDEN",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "TOQUE2-LOTE-A",
  "touch_no": 2,
  "recipient": "booking@leigardengroup.com",
  "language": "en",
  "sent_at": "2026-08-28",
  "status": "enviado",
  "note": "toque 2"
 },
 {
  "gmail_id": "1a048bfe5b07b2f7",
  "restaurant_id": "43298",
  "restaurant_name": "IL SANLORENZO",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "TOQUE2-LOTE-A",
  "touch_no": 2,
  "recipient": "info@ilsanlorenzo.it",
  "language": "it",
  "sent_at": "2026-08-28",
  "status": "enviado",
  "note": "toque 2"
 },
 {
  "gmail_id": "1a048c08e20297db",
  "restaurant_id": "16987",
  "restaurant_name": "ELEOS",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "TOQUE2-LOTE-A",
  "touch_no": 2,
  "recipient": "beyoglueleos@hotmail.com",
  "language": "en",
  "sent_at": "2026-08-28",
  "status": "enviado",
  "note": "toque 2 (respondeu ao toque 1"
 },
 {
  "gmail_id": "1a048c13ad0a138c",
  "restaurant_id": "35087",
  "restaurant_name": "EAT SIGHT STORY DECK",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "TOQUE2-LOTE-A",
  "touch_no": 2,
  "recipient": "service@salaarun.com",
  "language": "en",
  "sent_at": "2026-08-28",
  "status": "enviado",
  "note": "toque 2 (respondeu ao toque 1"
 },
 {
  "gmail_id": "1a048c2432442770",
  "restaurant_id": "254445",
  "restaurant_name": "LA BULLONA",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "TOQUE2-LOTE-A",
  "touch_no": 2,
  "recipient": "info@bullona.com",
  "language": "it",
  "sent_at": "2026-08-28",
  "status": "enviado",
  "note": "toque 2"
 },
 {
  "gmail_id": "1a048c2f56a656f9",
  "restaurant_id": "298865",
  "restaurant_name": "Menina Sardinha",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "TOQUE2-LOTE-A",
  "touch_no": 2,
  "recipient": "menina.sardinha@gmail.com",
  "language": "pt",
  "sent_at": "2026-08-28",
  "status": "enviado",
  "note": "toque 2"
 },
 {
  "gmail_id": "1a048c39c2715faf",
  "restaurant_id": "88557",
  "restaurant_name": "TIO PEPE",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "TOQUE2-LOTE-A",
  "touch_no": 2,
  "recipient": "miguel@restaurantetiopepe.com",
  "language": "en",
  "sent_at": "2026-08-28",
  "status": "enviado",
  "note": "toque 2"
 },
 {
  "gmail_id": "1a049427739c90a5",
  "restaurant_id": "15385",
  "restaurant_name": "THE LOBSTER HOUSE",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "TOQUE2-LOTE-A",
  "touch_no": 2,
  "recipient": "lobsterhouse@live.fr",
  "language": "fr",
  "sent_at": "2026-08-28",
  "status": "enviado",
  "note": "toque 2"
 },
 {
  "gmail_id": "1a0494959e68d541",
  "restaurant_id": "260033",
  "restaurant_name": "NAMMOS",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "TOQUE2-LOTE-A",
  "touch_no": 2,
  "recipient": "Reservations@nammos.ae",
  "language": "en",
  "sent_at": "2026-08-28",
  "status": "enviado",
  "note": "toque 2"
 },
 {
  "gmail_id": "1a0494ac3ea63d5c",
  "restaurant_id": "69949",
  "restaurant_name": "CASA DO PREGO",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "TOQUE2-LOTE-B",
  "touch_no": 1,
  "recipient": "info@casadoprego.com",
  "language": "pt",
  "sent_at": "2026-08-28",
  "status": "enviado",
  "note": "lote B - primeiro contato (texto toque 2)"
 },
 {
  "gmail_id": "1a049ac7845376c5",
  "restaurant_id": "70535",
  "restaurant_name": "O ANTÓNIO",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "TOQUE2-LOTE-B",
  "touch_no": 1,
  "recipient": "oantonio@restauranteoantonio.pt",
  "language": "pt",
  "sent_at": "2026-08-28",
  "status": "enviado",
  "note": "lote B - primeiro contato (texto toque 2)"
 },
 {
  "gmail_id": "1a049ad58ba4f28c",
  "restaurant_id": "79616",
  "restaurant_name": "LA CUCINA",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "TOQUE2-LOTE-B",
  "touch_no": 1,
  "recipient": "la.cucina06@gmail.com",
  "language": "fr",
  "sent_at": "2026-08-28",
  "status": "enviado",
  "note": "lote B - primeiro contato (texto toque 2)"
 },
 {
  "gmail_id": "1a049ae4b0ce4b78",
  "restaurant_id": "14328",
  "restaurant_name": "BILLIONAIRE",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "TOQUE2-LOTE-B",
  "touch_no": 1,
  "recipient": "contact@billionaire-gammarth.com",
  "language": "fr",
  "sent_at": "2026-08-28",
  "status": "enviado",
  "note": "lote B - primeiro contato (texto toque 2)"
 },
 {
  "gmail_id": "1a049b03e679f32c",
  "restaurant_id": "70105",
  "restaurant_name": "DON SEBASTIAO",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "TOQUE2-LOTE-B",
  "touch_no": 1,
  "recipient": "restaurante.dsebastiao@net.vodafone.pt",
  "language": "pt",
  "sent_at": "2026-08-28",
  "status": "bounce",
  "note": "lote B - primeiro contato (texto toque 2) - BOUNCE dominio inexistente"
 },
 {
  "gmail_id": "1a049b167ff4da89",
  "restaurant_id": "69928",
  "restaurant_name": "A PETISQUEIRA",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "TOQUE2-LOTE-B",
  "touch_no": 1,
  "recipient": "apetisqueiralagos@gmail.com",
  "language": "pt",
  "sent_at": "2026-08-28",
  "status": "enviado",
  "note": "lote B - primeiro contato (texto toque 2)"
 },
 {
  "gmail_id": "1a049c7c35c55e27",
  "restaurant_id": "70083",
  "restaurant_name": "MY SUSHI",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "TOQUE2-LOTE-B",
  "touch_no": 1,
  "recipient": "lilongfei807@gmail.com",
  "language": "pt",
  "sent_at": "2026-08-28",
  "status": "enviado",
  "note": "lote B - primeiro contato (texto toque 2)"
 },
 {
  "gmail_id": "1a049cb41cc7366f",
  "restaurant_id": "92055",
  "restaurant_name": "LA PETITE MAISON",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "TOQUE2-LOTE-B",
  "touch_no": 1,
  "recipient": "lapetitemaisonsaintemaxime@gmail.com",
  "language": "fr",
  "sent_at": "2026-08-28",
  "status": "enviado",
  "note": "lote B - primeiro contato (texto toque 2) (enviado pelo coordenador apos bloqueio)"
 },
 {
  "gmail_id": "1a049b753233fdce",
  "restaurant_id": "17053",
  "restaurant_name": "AROMA",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "TOQUE2-LOTE-B",
  "touch_no": 1,
  "recipient": "booking@aromarestaurant.it",
  "language": "it",
  "sent_at": "2026-08-28",
  "status": "enviado",
  "note": "lote B - primeiro contato (texto toque 2)"
 },
 {
  "gmail_id": "1a049cc12faa3aaa",
  "restaurant_id": "27603",
  "restaurant_name": "PUNY",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "TOQUE2-LOTE-B",
  "touch_no": 1,
  "recipient": "info@ristorantepunyportofino.com",
  "language": "it",
  "sent_at": "2026-08-28",
  "status": "enviado",
  "note": "lote B - primeiro contato (texto toque 2) (enviado pelo coordenador apos bloqueio)"
 },
 {
  "gmail_id": "1a049ba8d2156b83",
  "restaurant_id": "14068",
  "restaurant_name": "SKYE",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "TOQUE2-LOTE-B",
  "touch_no": 1,
  "recipient": "skye@hotelunique.com",
  "language": "pt",
  "sent_at": "2026-08-28",
  "status": "enviado",
  "note": "lote B - primeiro contato (texto toque 2)"
 },
 {
  "gmail_id": "1a049bb904bc4b4e",
  "restaurant_id": "10547",
  "restaurant_name": "PARTHENOPI",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "TOQUE2-LOTE-B",
  "touch_no": 1,
  "recipient": "parthenopicannes@gmail.com",
  "language": "fr",
  "sent_at": "2026-08-28",
  "status": "enviado",
  "note": "lote B - primeiro contato (texto toque 2)"
 },
 {
  "gmail_id": "1a049bce5f81da8c",
  "restaurant_id": "11977",
  "restaurant_name": "ASTRA",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "TOQUE2-LOTE-B",
  "touch_no": 1,
  "recipient": "contact@astra-mykonos.com",
  "language": "en",
  "sent_at": "2026-08-28",
  "status": "enviado",
  "note": "lote B - primeiro contato (texto toque 2)"
 },
 {
  "gmail_id": "1a049be379188715",
  "restaurant_id": "43268",
  "restaurant_name": "STRAVINSKIJ",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "TOQUE2-LOTE-B",
  "touch_no": 1,
  "recipient": "fb.derussie@roccofortehotels.com",
  "language": "it",
  "sent_at": "2026-08-28",
  "status": "enviado",
  "note": "lote B - primeiro contato (texto toque 2)"
 },
 {
  "gmail_id": "1a049bf6ba912b87",
  "restaurant_id": "69979",
  "restaurant_name": "SCARTUCCIO",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "TOQUE2-LOTE-B",
  "touch_no": 1,
  "recipient": "scartuccioapulianfood@gmail.com",
  "language": "pt",
  "sent_at": "2026-08-28",
  "status": "enviado",
  "note": "lote B - primeiro contato (texto toque 2)"
 },
 {
  "gmail_id": "1a049c0b143738dd",
  "restaurant_id": "57181",
  "restaurant_name": "PAPADAKIS",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "TOQUE2-LOTE-B",
  "touch_no": 1,
  "recipient": "info@papadakisrestaurant.com",
  "language": "en",
  "sent_at": "2026-08-28",
  "status": "enviado",
  "note": "lote B - primeiro contato (texto toque 2)"
 },
 {
  "gmail_id": "1a049c21b0a8efc3",
  "restaurant_id": "13331",
  "restaurant_name": "JOAQUINA",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "TOQUE2-LOTE-B",
  "touch_no": 1,
  "recipient": "joaquina@joaquinabar.com.br",
  "language": "pt",
  "sent_at": "2026-08-28",
  "status": "enviado",
  "note": "lote B - primeiro contato (texto toque 2)"
 },
 {
  "gmail_id": "1a049c2f6a1388dc",
  "restaurant_id": "16182",
  "restaurant_name": "MISHIGUENE",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "TOQUE2-LOTE-B",
  "touch_no": 1,
  "recipient": "reservas@mishiguene.com",
  "language": "es",
  "sent_at": "2026-08-28",
  "status": "enviado",
  "note": "lote B - primeiro contato (texto toque 2)"
 },
 {
  "gmail_id": "1a049c3be194b740",
  "restaurant_id": "16558",
  "restaurant_name": "KINGS JOY",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "TOQUE2-LOTE-B",
  "touch_no": 1,
  "recipient": "rsvp@kingsjoy.com",
  "language": "en",
  "sent_at": "2026-08-28",
  "status": "enviado",
  "note": "lote B - primeiro contato (texto toque 2)"
 },
 {
  "gmail_id": "1a049c4a6310f803",
  "restaurant_id": "70879",
  "restaurant_name": "ABRIGO",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "TOQUE2-LOTE-B",
  "touch_no": 1,
  "recipient": "gelanel@sapo.pt",
  "language": "pt",
  "sent_at": "2026-08-28",
  "status": "enviado",
  "note": "lote B - primeiro contato (texto toque 2)"
 },
 {
  "gmail_id": "1a049c5fec2e598c",
  "restaurant_id": "70461",
  "restaurant_name": "CAMPIMAR",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "TOQUE2-LOTE-B",
  "touch_no": 1,
  "recipient": "campimar@grupoadm.pt",
  "language": "pt",
  "sent_at": "2026-08-28",
  "status": "enviado",
  "note": "lote B - primeiro contato (texto toque 2)"
 },
 {
  "gmail_id": "1a049c6dd5376516",
  "restaurant_id": "24780",
  "restaurant_name": "BUCA MARIO",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "TOQUE2-LOTE-B",
  "touch_no": 1,
  "recipient": "bucamario@bucamario.it",
  "language": "it",
  "sent_at": "2026-08-28",
  "status": "enviado",
  "note": "lote B - primeiro contato (texto toque 2)"
 },
 {
  "gmail_id": "1a058aff10edb7b1",
  "restaurant_id": "53545",
  "restaurant_name": "TRATTORIA DEL TRIBUNALE",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L1",
  "touch_no": 1,
  "recipient": "info@trattoriadeltribunale.it",
  "language": "it",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L1 - link rastreado - prazo 10/09"
 },
 {
  "gmail_id": "1a058b1d53c02e1f",
  "restaurant_id": "76045",
  "restaurant_name": "LA MORUE",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L1",
  "touch_no": 1,
  "recipient": "restaurantlamorue@gmail.com",
  "language": "fr",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L1 - link rastreado - prazo 10/09"
 },
 {
  "gmail_id": "1a058b290d5999e1",
  "restaurant_id": "44602",
  "restaurant_name": "GREEN TEA",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L1",
  "touch_no": 1,
  "recipient": "info@green-tea.it",
  "language": "it",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L1 - link rastreado - prazo 10/09"
 },
 {
  "gmail_id": "1a058b3fe914fc5b",
  "restaurant_id": "43043",
  "restaurant_name": "LE JARDIN DE RUSSIE",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L1",
  "touch_no": 1,
  "recipient": "fb.derussie@roccofortehotels.com",
  "language": "it",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L1 - link rastreado - prazo 10/09"
 },
 {
  "gmail_id": "1a058b489c917942",
  "restaurant_id": "72138",
  "restaurant_name": "HANAM PIG HOUSE",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L1",
  "touch_no": 1,
  "recipient": "kdh@hanamfnb.co.kr",
  "language": "en",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L1 - link rastreado - prazo 10/09"
 },
 {
  "gmail_id": "1a058b794ac2610e",
  "restaurant_id": "71720",
  "restaurant_name": "LA TABLE DE MARIE",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L1",
  "touch_no": 1,
  "recipient": "restaurantlatabledemarie@gmail.com",
  "language": "fr",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L1 - link rastreado - prazo 10/09"
 },
 {
  "gmail_id": "1a058b819ed5f43b",
  "restaurant_id": "11732",
  "restaurant_name": "TAUSEND",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L1",
  "touch_no": 1,
  "recipient": "host@tausendberlin.com",
  "language": "en",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L1 - link rastreado - prazo 10/09"
 },
 {
  "gmail_id": "1a058b93536e7a43",
  "restaurant_id": "87832",
  "restaurant_name": "LE COQ ROUGE",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L1",
  "touch_no": 1,
  "recipient": "lecoqrouge.reims@gmail.com",
  "language": "fr",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L1 - link rastreado - prazo 10/09"
 },
 {
  "gmail_id": "1a058b9ccb74c562",
  "restaurant_id": "69843",
  "restaurant_name": "REPOLHO",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L1",
  "touch_no": 1,
  "recipient": "repolhogastrobar@gmail.com",
  "language": "pt",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L1 - link rastreado - prazo 10/09"
 },
 {
  "gmail_id": "1a058bae4b5230cb",
  "restaurant_id": "40772",
  "restaurant_name": "PLUM",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L1",
  "touch_no": 1,
  "recipient": "rsvn@capesienna.com",
  "language": "en",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L1 - link rastreado - prazo 10/09"
 },
 {
  "gmail_id": "1a058bb8cab2a19c",
  "restaurant_id": "28284",
  "restaurant_name": "Onyx",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L1",
  "touch_no": 1,
  "recipient": "onyx@doco.com",
  "language": "en",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L1 - link rastreado - prazo 10/09"
 },
 {
  "gmail_id": "1a058bcc9febf8ce",
  "restaurant_id": "69845",
  "restaurant_name": "LUCA’S",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L1",
  "touch_no": 1,
  "recipient": "lucasrooftop@gmail.com",
  "language": "pt",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L1 - link rastreado - prazo 10/09"
 },
 {
  "gmail_id": "1a058bd78071dca7",
  "restaurant_id": "14728",
  "restaurant_name": "LE PLONGEOIR",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L1",
  "touch_no": 1,
  "recipient": "contact@leplongeoir.com",
  "language": "fr",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L1 - link rastreado - prazo 10/09"
 },
 {
  "gmail_id": "1a058beae490f859",
  "restaurant_id": "294208",
  "restaurant_name": "Bar Josephine",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L1",
  "touch_no": 1,
  "recipient": "molut-barjosephine@mohg.com",
  "language": "fr",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L1 - link rastreado - prazo 10/09"
 },
 {
  "gmail_id": "1a058bee442a49de",
  "restaurant_id": "16199",
  "restaurant_name": "Fervor",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L1",
  "touch_no": 1,
  "recipient": "operaciones@sottovoce.com.ar",
  "language": "es",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L1 - link rastreado - prazo 10/09"
 },
 {
  "gmail_id": "1a058c011c258eb2",
  "restaurant_id": "14458",
  "restaurant_name": "GIGI",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L1",
  "touch_no": 1,
  "recipient": "contact@gigi-restaurant.com",
  "language": "fr",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L1 - link rastreado - prazo 10/09"
 },
 {
  "gmail_id": "1a058c0afe262f07",
  "restaurant_id": "17490",
  "restaurant_name": "THREE SIXTY",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L1",
  "touch_no": 1,
  "recipient": "threesixty@thetorchdoha.com",
  "language": "en",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L1 - link rastreado - prazo 10/09"
 },
 {
  "gmail_id": "1a058c21fb65240a",
  "restaurant_id": "11844",
  "restaurant_name": "THE SANCTUARY",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L1",
  "touch_no": 1,
  "recipient": "roma@thesanctuaryecoretreat.com",
  "language": "it",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L1 - link rastreado - prazo 10/09"
 },
 {
  "gmail_id": "1a058c2a1759084e",
  "restaurant_id": "71163",
  "restaurant_name": "LE PETIT VINCENT",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L1",
  "touch_no": 1,
  "recipient": "chezvincentbastia@orange.fr",
  "language": "fr",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L1 - link rastreado - prazo 10/09"
 },
 {
  "gmail_id": "1a058c3f694629d1",
  "restaurant_id": "43967",
  "restaurant_name": "SUAN SUAN",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L1",
  "touch_no": 1,
  "recipient": "suansuan_au@hotmail.com",
  "language": "en",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L1 - link rastreado - prazo 10/09"
 },
 {
  "gmail_id": "1a058c450ad72b9f",
  "restaurant_id": "75395",
  "restaurant_name": "GURU",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L1",
  "touch_no": 1,
  "recipient": "contact@leguru.fr",
  "language": "fr",
  "sent_at": "2026-08-31",
  "status": "bounce",
  "note": "coorte L1 - link rastreado - prazo 10/09 - BOUNCE caixa inexistente"
 },
 {
  "gmail_id": "1a058c8b6eaad98c",
  "restaurant_id": "84710",
  "restaurant_name": "BOATHOUSE AT HENDRY'S",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L1",
  "touch_no": 1,
  "recipient": "brendan@boathousesb.com",
  "language": "en",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L1 - link rastreado - prazo 10/09"
 },
 {
  "gmail_id": "1a058c61ce39893d",
  "restaurant_id": "43401",
  "restaurant_name": "IL TEMPIO DI ISIDE",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L1",
  "touch_no": 1,
  "recipient": "tempioisideristorante@gmail.com",
  "language": "it",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L1 - link rastreado - prazo 10/09"
 },
 {
  "gmail_id": "1a058c6e665798f4",
  "restaurant_id": "52907",
  "restaurant_name": "THE CLOUD",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L1",
  "touch_no": 1,
  "recipient": "samanncloudrestaurant@gmail.com",
  "language": "en",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L1 - link rastreado - prazo 10/09"
 },
 {
  "gmail_id": "1a058c7fa3484c2f",
  "restaurant_id": "45387",
  "restaurant_name": "TERRAZZA BORROMINI",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L1",
  "touch_no": 1,
  "recipient": "prenotazioniterrazze@gmail.com",
  "language": "it",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L1 - link rastreado - prazo 10/09"
 },
 {
  "gmail_id": "1a058c984bf98eaf",
  "restaurant_id": "87212",
  "restaurant_name": "LA COUR DU LOUVRE",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L1",
  "touch_no": 1,
  "recipient": "contact@restaurantlacourdulouvre.fr",
  "language": "fr",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L1 - link rastreado - prazo 10/09"
 },
 {
  "gmail_id": "1a058ca39a551491",
  "restaurant_id": "83040",
  "restaurant_name": "GAJOS D’OURO",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L1",
  "touch_no": 1,
  "recipient": "biancateixeira@btcom.com.br",
  "language": "pt",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L1 - link rastreado - prazo 10/09"
 },
 {
  "gmail_id": "1a058cb3bbc4c565",
  "restaurant_id": "39305",
  "restaurant_name": "SONAMU",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L1",
  "touch_no": 1,
  "recipient": "info@sonamu-frankfurt.de",
  "language": "en",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L1 - link rastreado - prazo 10/09"
 },
 {
  "gmail_id": "1a058f699c2b450f",
  "restaurant_id": "76485",
  "restaurant_name": "DOMA",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L1",
  "touch_no": 1,
  "recipient": "domacompany@naver.com",
  "language": "en",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L1 - link rastreado - prazo 10/09"
 },
 {
  "gmail_id": "1a058cc8c52eb083",
  "restaurant_id": "79067",
  "restaurant_name": "EPIRO",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L1",
  "touch_no": 1,
  "recipient": "epironice@gmail.com",
  "language": "fr",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L1 - link rastreado - prazo 10/09"
 },
 {
  "gmail_id": "1a058cd6d4cb2599",
  "restaurant_id": "34760",
  "restaurant_name": "SOU OMAKASE",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L1",
  "touch_no": 1,
  "recipient": "sou.omakase@gmail.com",
  "language": "en",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L1 - link rastreado - prazo 10/09"
 },
 {
  "gmail_id": "1a05943dc8bd5872",
  "restaurant_id": "35239",
  "restaurant_name": "BAAN SOMTUM SATHORN",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L1",
  "touch_no": 1,
  "recipient": "booking@baansomtum.com",
  "language": "en",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L1 - link rastreado - prazo 10/09"
 },
 {
  "gmail_id": "1a0593eda9c46845",
  "restaurant_id": "43981",
  "restaurant_name": "PASSATA LA MORETTA",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L1",
  "touch_no": 1,
  "recipient": "info@passatalamoretta.it",
  "language": "it",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L1 - link rastreado - prazo 10/09"
 },
 {
  "gmail_id": "1a0593fd6e2bd29e",
  "restaurant_id": "15796",
  "restaurant_name": "AU CHEVAL",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L1",
  "touch_no": 1,
  "recipient": "contact@auchevalchicago.com",
  "language": "en",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L1 - link rastreado - prazo 10/09"
 },
 {
  "gmail_id": "1a05944a280cfd16",
  "restaurant_id": "90888",
  "restaurant_name": "FURCA",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L1",
  "touch_no": 1,
  "recipient": "info@furca.cr",
  "language": "en",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L1 - link rastreado - prazo 10/09"
 },
 {
  "gmail_id": "1a0596e7fb179c09",
  "restaurant_id": "76676",
  "restaurant_name": "WOO TENDER",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "RESPOSTA-DIRETA",
  "touch_no": 3,
  "recipient": "wootender@gmail.com",
  "language": "en",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "resposta pessoal de Marlon no template - falta 1 passo (codigo no formulario) - thread do dono Jeongwoo Yun"
 },
 {
  "gmail_id": "1a059be6d7ee0570",
  "restaurant_id": "57227",
  "restaurant_name": "ORIZONTES",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L2",
  "touch_no": 1,
  "recipient": "reservation@kastelorizo.com.gr",
  "language": "en",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L2 - link rastreado c=fundadores-l2 - prazo 10/09"
 },
 {
  "gmail_id": "1a059bfb22475760",
  "restaurant_id": "40943",
  "restaurant_name": "Haidilao Hotpot",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L2",
  "touch_no": 1,
  "recipient": "ygppb@haidilao.com",
  "language": "en",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L2 - link rastreado c=fundadores-l2 - prazo 10/09"
 },
 {
  "gmail_id": "1a059c10677ec508",
  "restaurant_id": "24993",
  "restaurant_name": "L'EVANGELISTA",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L2",
  "touch_no": 1,
  "recipient": "info@ristorantelevangelista.it",
  "language": "it",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L2 - link rastreado c=fundadores-l2 - prazo 10/09"
 },
 {
  "gmail_id": "1a059c221f9c32ab",
  "restaurant_id": "16159",
  "restaurant_name": "Don Julio",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L2",
  "touch_no": 1,
  "recipient": "info@parrilladonjulio.com.ar",
  "language": "es",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L2 - link rastreado c=fundadores-l2 - prazo 10/09"
 },
 {
  "gmail_id": "1a059c36427a696b",
  "restaurant_id": "79669",
  "restaurant_name": "PRIMO AMORE BY PAPPAGALLO",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L2",
  "touch_no": 1,
  "recipient": "contact@pappagallo.co",
  "language": "fr",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L2 - link rastreado c=fundadores-l2 - prazo 10/09"
 },
 {
  "gmail_id": "1a059c46a6725275",
  "restaurant_id": "14674",
  "restaurant_name": "THE POLO BAR",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L2",
  "touch_no": 1,
  "recipient": "reservations@polobarralphlauren.com",
  "language": "en",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L2 - link rastreado c=fundadores-l2 - prazo 10/09"
 },
 {
  "gmail_id": "1a059c5adb76614e",
  "restaurant_id": "96653",
  "restaurant_name": "OHMS",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L2",
  "touch_no": 1,
  "recipient": "mary@ohmscafe.com",
  "language": "en",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L2 - link rastreado c=fundadores-l2 - prazo 10/09"
 },
 {
  "gmail_id": "1a059c71625b5718",
  "restaurant_id": "33956",
  "restaurant_name": "EM",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L2",
  "touch_no": 1,
  "recipient": "hello@emilia.rest",
  "language": "es",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L2 - link rastreado c=fundadores-l2 - prazo 10/09"
 },
 {
  "gmail_id": "1a059c8718f24a33",
  "restaurant_id": "14570",
  "restaurant_name": "LE JULES VERNE",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L2",
  "touch_no": 1,
  "recipient": "reservation.jv@lejulesverne-paris.com",
  "language": "fr",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L2 - link rastreado c=fundadores-l2 - prazo 10/09"
 },
 {
  "gmail_id": "1a059c9aa56ce018",
  "restaurant_id": "70345",
  "restaurant_name": "VENEZA",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L2",
  "touch_no": 1,
  "recipient": "restaurantevenezalagos@gmail.com",
  "language": "pt",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L2 - link rastreado c=fundadores-l2 - prazo 10/09"
 },
 {
  "gmail_id": "1a059cac45eb91cd",
  "restaurant_id": "87769",
  "restaurant_name": "L'ALAMBIC",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L2",
  "touch_no": 1,
  "recipient": "alambic.restaurant@orange.fr",
  "language": "fr",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L2 - link rastreado c=fundadores-l2 - prazo 10/09"
 },
 {
  "gmail_id": "1a059cbe2f0849c4",
  "restaurant_id": "83050",
  "restaurant_name": "NAGA",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L2",
  "touch_no": 1,
  "recipient": "nagayama@nagayama.com.br",
  "language": "pt",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L2 - link rastreado c=fundadores-l2 - prazo 10/09"
 },
 {
  "gmail_id": "1a059cd2d030a1ea",
  "restaurant_id": "17051",
  "restaurant_name": "TRATTORIA AL MORO",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L2",
  "touch_no": 1,
  "recipient": "info@ristorantealmororoma.it",
  "language": "it",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L2 - link rastreado c=fundadores-l2 - prazo 10/09"
 },
 {
  "gmail_id": "1a059ce6a52f8a98",
  "restaurant_id": "67058",
  "restaurant_name": "VIKING'S WHARF",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L2",
  "touch_no": 1,
  "recipient": "hjkong@akgroup.co.kr",
  "language": "en",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L2 - link rastreado c=fundadores-l2 - prazo 10/09"
 },
 {
  "gmail_id": "1a059cf8be6e892b",
  "restaurant_id": "42820",
  "restaurant_name": "AI PIANI",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L2",
  "touch_no": 1,
  "recipient": "aipiani@yahoo.it",
  "language": "it",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L2 - link rastreado c=fundadores-l2 - prazo 10/09"
 },
 {
  "gmail_id": "1a059d0a2d98587d",
  "restaurant_id": "23624",
  "restaurant_name": "Oslo Court",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L2",
  "touch_no": 1,
  "recipient": "oslorestaurant@gmail.com",
  "language": "en",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L2 - link rastreado c=fundadores-l2 - prazo 10/09"
 },
 {
  "gmail_id": "1a059d17568a7442",
  "restaurant_id": "25142",
  "restaurant_name": "KIKU",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L2",
  "touch_no": 1,
  "recipient": "kikumayfair@kikurestaurant.co.uk",
  "language": "en",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L2 - link rastreado c=fundadores-l2 - prazo 10/09"
 },
 {
  "gmail_id": "1a059d2b639b6500",
  "restaurant_id": "16560",
  "restaurant_name": "CHINA GRILL",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L2",
  "touch_no": 1,
  "recipient": "chinagrill.park.beijing@hyatt.com",
  "language": "en",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L2 - link rastreado c=fundadores-l2 - prazo 10/09"
 },
 {
  "gmail_id": "1a059d3d6ceb7e9a",
  "restaurant_id": "83615",
  "restaurant_name": "WHITE RABBIT",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L2",
  "touch_no": 1,
  "recipient": "white.rabbit@wrf.su",
  "language": "en",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L2 - link rastreado c=fundadores-l2 - prazo 10/09"
 },
 {
  "gmail_id": "1a059beca9179305",
  "restaurant_id": "41014",
  "restaurant_name": "BABA NEST",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L2",
  "touch_no": 1,
  "recipient": "chill@sripanwa.com",
  "language": "en",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L2 - link rastreado c=fundadores-l2 - prazo 10/09"
 },
 {
  "gmail_id": "1a059bfff236148f",
  "restaurant_id": "35700",
  "restaurant_name": "SORN",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L2",
  "touch_no": 1,
  "recipient": "reservation@sornfinesouthern.com",
  "language": "en",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L2 - link rastreado c=fundadores-l2 - prazo 10/09"
 },
 {
  "gmail_id": "1a059c13ecb2a802",
  "restaurant_id": "13291",
  "restaurant_name": "ISABEL LOUNGE",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L2",
  "touch_no": 1,
  "recipient": "eventos.copa@hilton.com",
  "language": "pt",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L2 - link rastreado c=fundadores-l2 - prazo 10/09"
 },
 {
  "gmail_id": "1a059c2511661d04",
  "restaurant_id": "13071",
  "restaurant_name": "LA TABLE DU TRAPPEUR",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L2",
  "touch_no": 1,
  "recipient": "contact@chaletsaintgeorges.com",
  "language": "fr",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L2 - link rastreado c=fundadores-l2 - prazo 10/09"
 },
 {
  "gmail_id": "1a059c36fe9a3cc0",
  "restaurant_id": "86285",
  "restaurant_name": "UZBEKISTAN",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L2",
  "touch_no": 1,
  "recipient": "info@uzbek-rest.ru",
  "language": "en",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L2 - link rastreado c=fundadores-l2 - prazo 10/09"
 },
 {
  "gmail_id": "1a059c49d233900f",
  "restaurant_id": "86294",
  "restaurant_name": "SIXTY",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L2",
  "touch_no": 1,
  "recipient": "sixtyrestaurant@gmail.com",
  "language": "en",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L2 - link rastreado c=fundadores-l2 - prazo 10/09"
 },
 {
  "gmail_id": "1a059c5af1954c9f",
  "restaurant_id": "57139",
  "restaurant_name": "GB ROOF GARDEN",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L2",
  "touch_no": 1,
  "recipient": "grandebretagne.restaurants@luxurycollection.com",
  "language": "en",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L2 - link rastreado c=fundadores-l2 - prazo 10/09"
 },
 {
  "gmail_id": "1a059c6afc9eb22e",
  "restaurant_id": "19438",
  "restaurant_name": "LA CLOSERIE",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L2",
  "touch_no": 1,
  "recipient": "lacloserie2@yahoo.fr",
  "language": "fr",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L2 - link rastreado c=fundadores-l2 - prazo 10/09"
 },
 {
  "gmail_id": "1a059c7cdf3e94dd",
  "restaurant_id": "17019",
  "restaurant_name": "Karaköy Lokantası",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L2",
  "touch_no": 1,
  "recipient": "info@karakoylokantasi.com",
  "language": "en",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L2 - link rastreado c=fundadores-l2 - prazo 10/09"
 },
 {
  "gmail_id": "1a059c90bdc27ff0",
  "restaurant_id": "87797",
  "restaurant_name": "SHIN'ZEN",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L2",
  "touch_no": 1,
  "recipient": "restaurantshinzen@gmail.com",
  "language": "fr",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L2 - link rastreado c=fundadores-l2 - prazo 10/09"
 },
 {
  "gmail_id": "1a059ca1a197d3fe",
  "restaurant_id": "22751",
  "restaurant_name": "LE BOLOGNE",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L2",
  "touch_no": 1,
  "recipient": "info@lebologne.com",
  "language": "fr",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L2 - link rastreado c=fundadores-l2 - prazo 10/09"
 },
 {
  "gmail_id": "1a059cb16c86df3c",
  "restaurant_id": "29640",
  "restaurant_name": "RED HEIFER",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L2",
  "touch_no": 1,
  "recipient": "redheifersteakhouse@gmail.com",
  "language": "en",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L2 - link rastreado c=fundadores-l2 - prazo 10/09"
 },
 {
  "gmail_id": "1a059cc49b172d1d",
  "restaurant_id": "32149",
  "restaurant_name": "PUJOL",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L2",
  "touch_no": 1,
  "recipient": "reservaciones@pujol.com.mx",
  "language": "es",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L2 - link rastreado c=fundadores-l2 - prazo 10/09"
 },
 {
  "gmail_id": "1a059cd494ce60b1",
  "restaurant_id": "73496",
  "restaurant_name": "L'AMANT SECRET",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L2",
  "touch_no": 1,
  "recipient": "contact@lescapehotel.com",
  "language": "en",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L2 - link rastreado c=fundadores-l2 - prazo 10/09"
 },
 {
  "gmail_id": "1a059ce1a17b16ad",
  "restaurant_id": "10507",
  "restaurant_name": "PEARL BEACH",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L2",
  "touch_no": 1,
  "recipient": "contact@thepearlbeach.com",
  "language": "fr",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L2 - link rastreado c=fundadores-l2 - prazo 10/09"
 },
 {
  "gmail_id": "1a059ceef9d02e4c",
  "restaurant_id": "19649",
  "restaurant_name": "LES QUATRE VENTS",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L2",
  "touch_no": 1,
  "recipient": "les4vents2a@gmail.com",
  "language": "fr",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L2 - link rastreado c=fundadores-l2 - prazo 10/09"
 },
 {
  "gmail_id": "1a059d012fb6c7cd",
  "restaurant_id": "16564",
  "restaurant_name": "CARGO HOLD",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L2",
  "touch_no": 1,
  "recipient": "cargohold@ushakamarineworld.co.za",
  "language": "en",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L2 - link rastreado c=fundadores-l2 - prazo 10/09"
 },
 {
  "gmail_id": "1a059d13ab207439",
  "restaurant_id": "83522",
  "restaurant_name": "Dar Yacout",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L2",
  "touch_no": 1,
  "recipient": "restaurantyacout@gmail.com",
  "language": "fr",
  "sent_at": "2026-08-31",
  "status": "enviado",
  "note": "coorte L2 - link rastreado c=fundadores-l2 - prazo 10/09"
 },
 {
  "gmail_id": "1a05ca89c04dd6ba",
  "restaurant_id": "71722",
  "restaurant_name": "LA TABLE DU VATICAN",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L3",
  "touch_no": 1,
  "recipient": "latableduvatican@gmail.com",
  "language": "fr",
  "sent_at": "2026-09-01",
  "status": "enviado",
  "note": "coorte L3 - link rastreado c=fundadores-l3 - prazo 10/09"
 },
 {
  "gmail_id": "1a05caa0cbe198c9",
  "restaurant_id": "16401",
  "restaurant_name": "ZAZÁ",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L3",
  "touch_no": 1,
  "recipient": "leblon.gerencia@zazabistro.com.br",
  "language": "pt",
  "sent_at": "2026-09-01",
  "status": "enviado",
  "note": "coorte L3 - link rastreado c=fundadores-l3 - prazo 10/09"
 },
 {
  "gmail_id": "1a05cab6370aa4f0",
  "restaurant_id": "70463",
  "restaurant_name": "DOM VINHO",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L3",
  "touch_no": 1,
  "recipient": "restaurantedomvinho@gmail.com",
  "language": "pt",
  "sent_at": "2026-09-01",
  "status": "enviado",
  "note": "coorte L3 - link rastreado c=fundadores-l3 - prazo 10/09"
 },
 {
  "gmail_id": "1a05cac55feee725",
  "restaurant_id": "15623",
  "restaurant_name": "KŌST",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L3",
  "touch_no": 1,
  "recipient": "info@kosttoronto.com",
  "language": "en",
  "sent_at": "2026-09-01",
  "status": "enviado",
  "note": "coorte L3 - link rastreado c=fundadores-l3 - prazo 10/09"
 },
 {
  "gmail_id": "1a05cad75acedb94",
  "restaurant_id": "70131",
  "restaurant_name": "THE CURRY LEAF",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L3",
  "touch_no": 1,
  "recipient": "rajeevchef1985@yahoo.com",
  "language": "pt",
  "sent_at": "2026-09-01",
  "status": "enviado",
  "note": "coorte L3 - link rastreado c=fundadores-l3 - prazo 10/09"
 },
 {
  "gmail_id": "1a05cae760db25d1",
  "restaurant_id": "72893",
  "restaurant_name": "OSTERIA DE ROMA",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L3",
  "touch_no": 1,
  "recipient": "osteriaderomaplaya@gmail.com",
  "language": "es",
  "sent_at": "2026-09-01",
  "status": "enviado",
  "note": "coorte L3 - link rastreado c=fundadores-l3 - prazo 10/09"
 },
 {
  "gmail_id": "1a05caf85cac75f6",
  "restaurant_id": "35200",
  "restaurant_name": "THE LOCAL",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L3",
  "touch_no": 1,
  "recipient": "info@thelocalthaicuisine.com",
  "language": "en",
  "sent_at": "2026-09-01",
  "status": "enviado",
  "note": "coorte L3 - link rastreado c=fundadores-l3 - prazo 10/09"
 },
 {
  "gmail_id": "1a05cb0a022d6a60",
  "restaurant_id": "16975",
  "restaurant_name": "BEYTI",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L3",
  "touch_no": 1,
  "recipient": "rezervasyon@beyti.com",
  "language": "en",
  "sent_at": "2026-09-01",
  "status": "enviado",
  "note": "coorte L3 - link rastreado c=fundadores-l3 - prazo 10/09"
 },
 {
  "gmail_id": "1a05cc04d0ceefd4",
  "restaurant_id": "16094",
  "restaurant_name": "HAKUSHU TEPPANYAKI",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L3",
  "touch_no": 1,
  "recipient": "hakushu.teppanyaki@gmail.com",
  "language": "en",
  "sent_at": "2026-09-01",
  "status": "enviado",
  "note": "coorte L3 - link rastreado c=fundadores-l3 - prazo 10/09 - enviado do loop principal (classificador)"
 },
 {
  "gmail_id": "1a05cb41092b6a45",
  "restaurant_id": "45955",
  "restaurant_name": "THAT'S AMORE",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L3",
  "touch_no": 1,
  "recipient": "info.thatsamorerestaurant@gmail.com",
  "language": "it",
  "sent_at": "2026-09-01",
  "status": "enviado",
  "note": "coorte L3 - link rastreado c=fundadores-l3 - prazo 10/09"
 },
 {
  "gmail_id": "1a05cc12e7a2a319",
  "restaurant_id": "17986",
  "restaurant_name": "BICE",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L3",
  "touch_no": 1,
  "recipient": "reservations@bicemilano.it",
  "language": "it",
  "sent_at": "2026-09-01",
  "status": "enviado",
  "note": "coorte L3 - link rastreado c=fundadores-l3 - prazo 10/09 - enviado do loop principal (classificador)"
 },
 {
  "gmail_id": "1a05cb73a8605f5a",
  "restaurant_id": "42912",
  "restaurant_name": "GIRARROSTO FIORENTINO",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L3",
  "touch_no": 1,
  "recipient": "info@girarrostofiorentino.it",
  "language": "it",
  "sent_at": "2026-09-01",
  "status": "enviado",
  "note": "coorte L3 - link rastreado c=fundadores-l3 - prazo 10/09"
 },
 {
  "gmail_id": "1a05cb8084837304",
  "restaurant_id": "16497",
  "restaurant_name": "TASHAS",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L3",
  "touch_no": 1,
  "recipient": "albateen@tashascafe.com",
  "language": "en",
  "sent_at": "2026-09-01",
  "status": "enviado",
  "note": "coorte L3 - link rastreado c=fundadores-l3 - prazo 10/09"
 },
 {
  "gmail_id": "1a05cb93c714dd7e",
  "restaurant_id": "69996",
  "restaurant_name": "NO PÁTIO",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L3",
  "touch_no": 1,
  "recipient": "rest.nopatio@gmail.com",
  "language": "pt",
  "sent_at": "2026-09-01",
  "status": "enviado",
  "note": "coorte L3 - link rastreado c=fundadores-l3 - prazo 10/09"
 },
 {
  "gmail_id": "1a05cba0b34ee457",
  "restaurant_id": "18025",
  "restaurant_name": "IL BARETTO",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L3",
  "touch_no": 1,
  "recipient": "info@ilbarettomilano.it",
  "language": "it",
  "sent_at": "2026-09-01",
  "status": "enviado",
  "note": "coorte L3 - link rastreado c=fundadores-l3 - prazo 10/09"
 },
 {
  "gmail_id": "1a05cc213feff56b",
  "restaurant_id": "43204",
  "restaurant_name": "Hamasei",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L3",
  "touch_no": 1,
  "recipient": "ristorantehamasei@yahoo.it",
  "language": "it",
  "sent_at": "2026-09-01",
  "status": "enviado",
  "note": "coorte L3 - link rastreado c=fundadores-l3 - prazo 10/09 - enviado do loop principal (classificador)"
 },
 {
  "gmail_id": "1a05cbd01ad1eb54",
  "restaurant_id": "36589",
  "restaurant_name": "FIREFLY BANGKOK",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L3",
  "touch_no": 1,
  "recipient": "foodandbeverage.sindhorn@kempinski.com",
  "language": "en",
  "sent_at": "2026-09-01",
  "status": "enviado",
  "note": "coorte L3 - link rastreado c=fundadores-l3 - prazo 10/09"
 },
 {
  "gmail_id": "1a05cbe0e2ffb33d",
  "restaurant_id": "44586",
  "restaurant_name": "PIERLUIGI",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L3",
  "touch_no": 1,
  "recipient": "info@pierluigi.it",
  "language": "it",
  "sent_at": "2026-09-01",
  "status": "enviado",
  "note": "coorte L3 - link rastreado c=fundadores-l3 - prazo 10/09"
 },
 {
  "gmail_id": "1a05ca8ef2732f1a",
  "restaurant_id": "21526",
  "restaurant_name": "Thirty8",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L3",
  "touch_no": 1,
  "recipient": "restaurant.kuagh@hyatt.com",
  "language": "en",
  "sent_at": "2026-09-01",
  "status": "enviado",
  "note": "coorte L3 - link rastreado c=fundadores-l3 - prazo 10/09"
 },
 {
  "gmail_id": "1a05caa1403f868d",
  "restaurant_id": "21528",
  "restaurant_name": "LAI PO HEEN",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L3",
  "touch_no": 1,
  "recipient": "mokul-reservations@mohg.com",
  "language": "en",
  "sent_at": "2026-09-01",
  "status": "enviado",
  "note": "coorte L3 - link rastreado c=fundadores-l3 - prazo 10/09"
 },
 {
  "gmail_id": "1a05cab2ec856076",
  "restaurant_id": "35166",
  "restaurant_name": "RUEN URAI",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L3",
  "touch_no": 1,
  "recipient": "therosehotelbkk@yahoo.com",
  "language": "en",
  "sent_at": "2026-09-01",
  "status": "enviado",
  "note": "coorte L3 - link rastreado c=fundadores-l3 - prazo 10/09"
 },
 {
  "gmail_id": "1a05cac5712ff50b",
  "restaurant_id": "24480",
  "restaurant_name": "Gymkhana",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L3",
  "touch_no": 1,
  "recipient": "info@gymkhanalondon.com",
  "language": "en",
  "sent_at": "2026-09-01",
  "status": "enviado",
  "note": "coorte L3 - link rastreado c=fundadores-l3 - prazo 10/09"
 },
 {
  "gmail_id": "1a05cadc6a1dec57",
  "restaurant_id": "69947",
  "restaurant_name": "ALMA LUSA",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L3",
  "touch_no": 1,
  "recipient": "almalusalagos@hotmail.com",
  "language": "pt",
  "sent_at": "2026-09-01",
  "status": "enviado",
  "note": "coorte L3 - link rastreado c=fundadores-l3 - prazo 10/09"
 },
 {
  "gmail_id": "1a05caeaf6897e79",
  "restaurant_id": "15591",
  "restaurant_name": "360 CN TOWER",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L3",
  "touch_no": 1,
  "recipient": "info@cntower.ca",
  "language": "en",
  "sent_at": "2026-09-01",
  "status": "enviado",
  "note": "coorte L3 - link rastreado c=fundadores-l3 - prazo 10/09"
 },
 {
  "gmail_id": "1a05caf9f10d597c",
  "restaurant_id": "10484",
  "restaurant_name": "MARCO LA ROSE DES VENTS",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L3",
  "touch_no": 1,
  "recipient": "info@larosedesvents.com",
  "language": "fr",
  "sent_at": "2026-09-01",
  "status": "enviado",
  "note": "coorte L3 - link rastreado c=fundadores-l3 - prazo 10/09"
 },
 {
  "gmail_id": "1a05cb08497375b3",
  "restaurant_id": "81590",
  "restaurant_name": "LOTUS CLUB",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L3",
  "touch_no": 1,
  "recipient": "zineb@lelotusclub.com",
  "language": "fr",
  "sent_at": "2026-09-01",
  "status": "enviado",
  "note": "coorte L3 - link rastreado c=fundadores-l3 - prazo 10/09"
 },
 {
  "gmail_id": "1a05cb1a72085de0",
  "restaurant_id": "68677",
  "restaurant_name": "TEA SCENT",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L3",
  "touch_no": 1,
  "recipient": "barteascent@gmail.com",
  "language": "en",
  "sent_at": "2026-09-01",
  "status": "enviado",
  "note": "coorte L3 - link rastreado c=fundadores-l3 - prazo 10/09"
 },
 {
  "gmail_id": "1a05cb2b80b9b910",
  "restaurant_id": "57214",
  "restaurant_name": "MS ROOF GARDEN",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L3",
  "touch_no": 1,
  "recipient": "roofgardenreservations@gmail.com",
  "language": "en",
  "sent_at": "2026-09-01",
  "status": "enviado",
  "note": "coorte L3 - link rastreado c=fundadores-l3 - prazo 10/09"
 },
 {
  "gmail_id": "1a05cb3ae28adcf7",
  "restaurant_id": "35171",
  "restaurant_name": "BAAN CHIANG",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L3",
  "touch_no": 1,
  "recipient": "baanchiang1986@gmail.com",
  "language": "en",
  "sent_at": "2026-09-01",
  "status": "enviado",
  "note": "coorte L3 - link rastreado c=fundadores-l3 - prazo 10/09"
 },
 {
  "gmail_id": "1a05cb4dea4fb49d",
  "restaurant_id": "253049",
  "restaurant_name": "MANÍ",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L3",
  "touch_no": 1,
  "recipient": "mani@manimanioca.com.br",
  "language": "pt",
  "sent_at": "2026-09-01",
  "status": "enviado",
  "note": "coorte L3 - link rastreado c=fundadores-l3 - prazo 10/09"
 },
 {
  "gmail_id": "1a05cb5cc16cd755",
  "restaurant_id": "24775",
  "restaurant_name": "BUCA LAPI",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L3",
  "touch_no": 1,
  "recipient": "bucalapi@gmail.com",
  "language": "it",
  "sent_at": "2026-09-01",
  "status": "enviado",
  "note": "coorte L3 - link rastreado c=fundadores-l3 - prazo 10/09"
 },
 {
  "gmail_id": "1a05cb6c16aa88d4",
  "restaurant_id": "39461",
  "restaurant_name": "ZUM GEMALTEN HAUS",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L3",
  "touch_no": 1,
  "recipient": "info@zumgemaltenhaus.de",
  "language": "en",
  "sent_at": "2026-09-01",
  "status": "enviado",
  "note": "coorte L3 - link rastreado c=fundadores-l3 - prazo 10/09"
 },
 {
  "gmail_id": "1a05cb7eda4c8d08",
  "restaurant_id": "37923",
  "restaurant_name": "THAI HERB",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L3",
  "touch_no": 1,
  "recipient": "thaiherbrestaurant@outlook.com",
  "language": "en",
  "sent_at": "2026-09-01",
  "status": "enviado",
  "note": "coorte L3 - link rastreado c=fundadores-l3 - prazo 10/09"
 },
 {
  "gmail_id": "1a05cb8b92170689",
  "restaurant_id": "87781",
  "restaurant_name": "LE CRYPTO",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L3",
  "touch_no": 1,
  "recipient": "restaurantlecrypto@free.fr",
  "language": "fr",
  "sent_at": "2026-09-01",
  "status": "enviado",
  "note": "coorte L3 - link rastreado c=fundadores-l3 - prazo 10/09"
 },
 {
  "gmail_id": "1a05cb9ddc604bf4",
  "restaurant_id": "17007",
  "restaurant_name": "ULUS 29",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L3",
  "touch_no": 1,
  "recipient": "info@29.com.tr",
  "language": "en",
  "sent_at": "2026-09-01",
  "status": "enviado",
  "note": "coorte L3 - link rastreado c=fundadores-l3 - prazo 10/09"
 },
 {
  "gmail_id": "1a05cbafb4641a8a",
  "restaurant_id": "16152",
  "restaurant_name": "La Cabrera",
  "campaign": "conta_profissional_fundadores_2026_08",
  "wave": "COORTE-L3",
  "touch_no": 1,
  "recipient": "info@lacabrera.com.ar",
  "language": "es",
  "sent_at": "2026-09-01",
  "status": "enviado",
  "note": "coorte L3 - link rastreado c=fundadores-l3 - prazo 10/09"
 }
];
