/**
 * emailText.ts — utilitários PUROS de texto de email (sem IO, sem config),
 * testáveis offline como historyTrim/waLimits.
 */

/**
 * Remove o histórico citado de um corpo de email, mantendo só o texto NOVO.
 * Corta no primeiro marcador de citação conhecido:
 *   - "Em <data>, <alguém> escreveu:" (pt) / "On ... wrote:" (en) /
 *     "Le ... a écrit :" (fr) / "El ... escribió:" (es)
 *   - "-----Original Message-----" / "---------- Forwarded message ---------"
 *   - bloco de cabeçalho citado ("From:"/"De:" seguido de "Sent:"/"Enviado:")
 * e descarta linhas restantes que começam com ">".
 */
export function stripQuotedReply(body: string): string {
  const lines = body.replace(/\r\n/g, "\n").split("\n");
  const cutMarkers: RegExp[] = [
    /^On .{4,80} wrote:\s*$/i,
    /^Em .{4,80} escreveu:\s*$/i,
    /^Le .{4,80} a écrit\s*:\s*$/i,
    /^El .{4,80} escribió:\s*$/i,
    /^-{2,}\s*Original Message\s*-{2,}$/i,
    /^-{2,}\s*Mensagem original\s*-{2,}$/i,
    /^-{2,}\s*Forwarded message\s*-{2,}$/i,
    /^_{10,}$/,
  ];

  let cut = lines.length;
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();
    if (cutMarkers.some((re) => re.test(line))) {
      cut = i;
      break;
    }
    // Cabeçalho citado: "From:/De:" seguido em até 3 linhas por outro header típico.
    if (/^(From|De):\s/i.test(line)) {
      const lookahead = lines.slice(i + 1, i + 4).map((l) => l.trim());
      if (lookahead.some((l) => /^(Sent|Date|Enviado|Enviada|Para|To|Subject|Assunto):\s/i.test(l))) {
        cut = i;
        break;
      }
    }
  }

  const fresh = lines
    .slice(0, cut)
    .filter((l) => !l.trimStart().startsWith(">"));

  return fresh.join("\n").trim();
}

/** Decodifica base64url (padrão do Gmail) para Buffer. */
export function decodeBase64Url(data: string): Buffer {
  const b64 = data.replace(/-/g, "+").replace(/_/g, "/");
  const padded = b64 + "=".repeat((4 - (b64.length % 4)) % 4);
  return Buffer.from(padded, "base64");
}

/** Codifica um header de email (Subject/From display) em RFC 2047 se preciso. */
export function encodeMimeHeader(value: string): string {
  // ASCII puro sem caracteres de controle → vai como está.
  if (/^[\x20-\x7e]*$/.test(value)) return value;
  return `=?UTF-8?B?${Buffer.from(value, "utf8").toString("base64")}?=`;
}

/**
 * Decodifica encoded-words RFC 2047 ("=?UTF-8?B?...?=" / "=?UTF-8?Q?...?=")
 * num header. O n8n às vezes entrega From/Subject SEM decodificar — e o lixo
 * resultante ("=?utf-8?q?noreply-...") derrotava as guardas de no-reply
 * (o padrão "noreply" não casa precedido de "?"), fazendo o agente responder
 * relatórios automáticos e queimar tokens. Tolerante: o que não decodificar
 * volta como veio.
 */
export function decodeRfc2047(value: string): string {
  if (!value || !value.includes("=?")) return value;
  return value
    // Espaço entre encoded-words adjacentes é ignorado por norma.
    .replace(/\?=\s+=\?/g, "?==?")
    .replace(/=\?([^?]+)\?([bBqQ])\?([^?]*)\?=/g, (_m, charset: string, enc: string, data: string) => {
      try {
        const bytes = /b/i.test(enc)
          ? Buffer.from(data, "base64")
          : Buffer.from(
              data
                .replace(/_/g, " ")
                .replace(/=([0-9A-Fa-f]{2})/g, (_x, h: string) => String.fromCharCode(parseInt(h, 16))),
              "latin1",
            );
        return /utf-?8/i.test(charset) ? bytes.toString("utf8") : bytes.toString("latin1");
      } catch {
        return data;
      }
    });
}

/** Extrai o endereço puro de um header From ("Nome <a@b.com>" → "a@b.com"). */
export function extractAddress(fromHeader: string): string | null {
  const decoded = decodeRfc2047(fromHeader);
  const angled = /<([^<>\s]+@[^<>\s]+)>/.exec(decoded);
  if (angled) return cleanAddress(angled[1]);
  const bare = /([^\s,;<>"]+@[^\s,;<>"]+)/.exec(decoded);
  return bare ? cleanAddress(bare[1]) : null;
}

/** Remove sobras de mangling ("=?utf-8?q?addr?=", aspas, "=" solto) das bordas. */
function cleanAddress(raw: string): string {
  return raw
    .toLowerCase()
    .replace(/^(=\?[^?]*\?[bq]\?|[=?'"\s]+)/i, "")
    .replace(/(\?=|[=?'"\s]+)$/i, "");
}

/** Extrai o nome de exibição de um header From, se houver. */
export function extractDisplayName(fromHeader: string): string | null {
  const m = /^\s*"?([^"<]+?)"?\s*</.exec(fromHeader);
  const name = m?.[1]?.trim();
  return name && name.length > 0 ? name : null;
}

/**
 * True quando o email é automático e NUNCA deve receber resposta
 * (auto-reply respondendo auto-reply = loop infinito).
 */
export function isAutoGenerated(headers: Record<string, string>): boolean {
  const h = (name: string) => (headers[name.toLowerCase()] ?? "").toLowerCase();
  if (h("auto-submitted") && h("auto-submitted") !== "no") return true;
  if (/^(bulk|junk|list|auto_reply)$/.test(h("precedence"))) return true;
  if (h("x-auto-response-suppress")) return true;
  if (h("x-autoreply") === "yes") return true;
  if (h("list-id") || h("list-unsubscribe")) return true;
  return false;
}

/** True para remetentes que não devem receber resposta (no-reply, daemons). */
export function isNoReplyAddress(address: string): boolean {
  return /(^|[._-])(no[._-]?reply|do[._-]?not[._-]?reply|mailer[._-]?daemon|postmaster|bounce)([._-]|@)/i.test(
    address,
  );
}

/**
 * Resolve em QUAL das nossas caixas o email chegou (multi-caixa via n8n).
 * Prioridade: campo "mailbox" explícito do fluxo n8n → endereço nosso presente
 * no header To → fallback (caixa principal). A resposta SEMPRE sai pela caixa
 * que recebeu — responder por outra quebraria o threading do Gmail (o
 * gmailMessageId só existe na caixa original).
 */
export function resolveMailbox(
  explicit: string | null,
  toHeader: string | null,
  ownAddresses: readonly string[],
  fallback: string,
): string {
  if (explicit) {
    const clean = explicit.toLowerCase().trim();
    if (ownAddresses.includes(clean)) return clean;
  }
  if (toHeader) {
    const to = decodeRfc2047(toHeader).toLowerCase();
    const hit = ownAddresses.find((a) => to.includes(a));
    if (hit) return hit;
  }
  return fallback;
}

/** Monta o assunto de resposta ("Re: X", sem empilhar Re: Re: Re:). */
export function replySubject(original: string | null): string {
  const s = (original ?? "").trim();
  if (!s) return "Re: The World Keys";
  return /^re\s*:/i.test(s) ? s : `Re: ${s}`;
}

/** Conversão simples HTML → texto (fallback quando não há text/plain). */
export function htmlToText(html: string): string {
  return html
    .replace(/<style[\s\S]*?<\/style>/gi, "")
    .replace(/<script[\s\S]*?<\/script>/gi, "")
    .replace(/<br\s*\/?>/gi, "\n")
    .replace(/<\/(p|div|tr|li|h[1-6])>/gi, "\n")
    .replace(/<[^>]+>/g, "")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

/** Heurística de assunto para auto-respostas quando os headers não vêm no payload. */
export function subjectLooksAutoReply(subject: string | null): boolean {
  return /^(automatic reply|auto[- ]?reply|resposta autom[aá]tica|r[eé]ponse automatique|respuesta autom[aá]tica|out of office|ausente|f[ée]rias|delivery status notification|undeliverable|mail delivery)/i.test(
    (subject ?? "").trim(),
  );
}

/**
 * Email de entrada normalizado — contrato do webhook /webhook/email (modo n8n).
 * `messageId` é o ID do Gmail (do Gmail Trigger), usado para dedup e para o nó
 * Gmail → Reply do n8n responder na mesma thread.
 */
export type InboundEmail = {
  from: string;
  fromName: string | null;
  subject: string | null;
  // Caixa NOSSA em que o email chegou (multi-caixa): campo "mailbox" explícito
  // do fluxo n8n, ou null (o servidor então tenta deduzir pelo header To).
  mailbox: string | null;
  // Header To cru (fallback para deduzir a caixa quando "mailbox" não vier).
  to: string | null;
  text: string;
  html: string;
  // Preview curto do Gmail (fallback quando não há corpo parseado).
  snippet: string;
  // Árvore MIME crua do Gmail (payload). Quando text/html vêm vazios, o
  // servidor extrai o corpo daqui — mesmo leitor do modo Gmail direto.
  payload: unknown;
  messageId: string;
  threadId: string | null;
  autoSubmitted: string | null;
  precedence: string | null;
  listId: string | null;
  attachments: Array<{ mimeType: string; data: string; filename?: string }>;
};

/**
 * Normaliza o payload vindo do n8n (Gmail Trigger → HTTP Request), tolerante a
 * variações de nome de campo. Retorna null quando faltam os essenciais
 * (remetente ou id da mensagem).
 */
export function normalizeInboundEmail(payload: unknown): InboundEmail | null {
  let p = payload as Record<string, unknown>;
  if (Array.isArray(p)) p = p[0] as Record<string, unknown>;
  if (p && typeof p === "object" && p.body && typeof p.body === "object") {
    p = p.body as Record<string, unknown>;
  }
  if (!p || typeof p !== "object") return null;

  const g = (...keys: string[]): string | null => {
    for (const k of keys) {
      const v = p[k];
      if (typeof v === "string" && v.trim()) return v.trim();
      if (typeof v === "number") return String(v);
    }
    return null;
  };

  // Headers podem chegar do n8n ainda em RFC 2047 ("=?UTF-8?Q?...?=") —
  // decodifica antes de qualquer guarda/extração.
  const rawFrom = decodeRfc2047(g("from", "From", "sender", "fromEmail", "from_email") ?? "");
  const from = extractAddress(rawFrom);
  const messageId = g("messageId", "message_id", "id", "gmailMessageId");
  if (!from || !messageId) return null;

  const rawAtt = (p.attachments ?? p.anexos) as unknown;
  const attachments: InboundEmail["attachments"] = Array.isArray(rawAtt)
    ? rawAtt
        .map((a) => {
          const o = a as Record<string, unknown>;
          const data = typeof o.data === "string" ? o.data : typeof o.content === "string" ? o.content : null;
          const mimeType =
            typeof o.mimeType === "string" ? o.mimeType : typeof o.mimetype === "string" ? o.mimetype : null;
          return data && mimeType
            ? { mimeType: mimeType.toLowerCase(), data, filename: typeof o.filename === "string" ? o.filename : undefined }
            : null;
        })
        .filter((a): a is NonNullable<typeof a> => a !== null)
    : [];

  // payload pode vir como objeto (embutido) ou string JSON (JSON.stringify no n8n).
  let payloadRaw: unknown = p.payload ?? null;
  if (typeof payloadRaw === "string") {
    try {
      payloadRaw = JSON.parse(payloadRaw);
    } catch {
      payloadRaw = null;
    }
  }

  const rawSubject = g("subject", "Subject");
  const rawName = g("fromName", "from_name");
  const rawMailbox = g("mailbox", "account", "box");
  return {
    from,
    fromName: rawName ? decodeRfc2047(rawName) : extractDisplayName(rawFrom),
    subject: rawSubject ? decodeRfc2047(rawSubject) : null,
    mailbox: rawMailbox ? (extractAddress(rawMailbox) ?? rawMailbox.toLowerCase()) : null,
    to: g("to", "To", "recipient"),
    text: g("text", "textPlain", "plainText", "body_text") ?? "",
    html: g("html", "textHtml", "htmlBody", "body_html") ?? "",
    snippet: g("snippet") ?? "",
    payload: payloadRaw,
    messageId,
    threadId: g("threadId", "thread_id"),
    autoSubmitted: g("autoSubmitted", "auto_submitted"),
    precedence: g("precedence"),
    listId: g("listId", "list_id"),
    attachments,
  };
}
