/**
 * emailChannel.ts — segunda "casca" da Aria: atendimento por EMAIL.
 *
 * Reaproveita todo o motor (runAgent, tools, sessões, fila, handoff, dedup);
 * este módulo só faz a ponte com a caixa Gmail (support@theworldkeys.com):
 *
 *   • POLLING via Gmail API (users.messages.list, q="in:inbox is:unread") a
 *     cada EMAIL_POLL_SECONDS — email tolera latência; polling é mais simples
 *     e robusto que push/Pub-Sub.
 *   • Cada email vira um turno: texto novo (histórico citado removido) +
 *     anexos de imagem/PDF como blocos multimodais.
 *   • Resposta enviada pela própria Gmail API na MESMA thread (In-Reply-To/
 *     References + threadId) — DKIM/SPF corretos e cópia em Enviados para o
 *     time acompanhar.
 *   • Guardas anti-loop: nunca responde auto-replies (Auto-Submitted,
 *     Precedence: bulk/list), remetentes no-reply/daemon, nem a própria caixa.
 *   • Identidade confiável = endereço do remetente (ver identity.ts); a chave
 *     de conversa é "email:<addr>" em toda a stack (fila, sessões, dashboard).
 *
 * DESLIGADO por padrão — liga com EMAIL_ENABLED=true + credenciais OAuth
 * (GMAIL_CLIENT_ID/SECRET/REFRESH_TOKEN com escopo gmail.modify).
 */

import axios from "axios";
import type Anthropic from "@anthropic-ai/sdk";
import { config } from "./config.js";
import { runAgent } from "./claude.js";
import { emailChatId, emailIdentity } from "./identity.js";
import { getOrRestoreHistory, setHistory } from "./sessions.js";
import { enqueueMessage } from "./conversationQueue.js";
import { isHumanControlled } from "./handoff.js";
import { isOutOfScope, textFromBlocks } from "./scopeScreen.js";
import {
  markMessageProcessed,
  savePendingEmail,
  clearPendingEmails,
  loadPendingEmails,
} from "./db.js";
import { sanitizeEmailReply, looksLikeInternalNote } from "./format.js";
import { recallMemories } from "./embeddings.js";
import { resolveProfileKey } from "./identity.js";
import { renderEmailHtml } from "./emailTemplate.js";
import { logMessage, logScopeBlock } from "./dashboard/logger.js";
import type { AriaContentBlock } from "./webhook.js";
import {
  decodeBase64Url,
  encodeMimeHeader,
  extractAddress,
  extractDisplayName,
  htmlToText,
  isAutoGenerated,
  isNoReplyAddress,
  normalizeInboundEmail,
  replySubject,
  resolveMailbox,
  stripQuotedReply,
  subjectLooksAutoReply,
} from "./emailText.js";

const GMAIL_BASE = "https://gmail.googleapis.com/gmail/v1/users/me";
const MAX_ATTACHMENT_BYTES = 8 * 1024 * 1024; // acima disso, ignora o anexo

// Todas as NOSSAS caixas (principal + extras vigiadas via n8n). Usado para
// nunca responder a nós mesmos e para resolver em qual caixa o email chegou.
const OWN_ADDRESSES: readonly string[] = [config.email.address, ...config.email.extraAddresses].filter(Boolean);

// ─── OAuth: access token via refresh token ───────────────────────────────────

let _token: { value: string; expiresAt: number } | null = null;

async function accessToken(): Promise<string> {
  if (_token && Date.now() < _token.expiresAt - 60_000) return _token.value;
  const { data } = await axios.post(
    "https://oauth2.googleapis.com/token",
    new URLSearchParams({
      client_id: config.email.clientId,
      client_secret: config.email.clientSecret,
      refresh_token: config.email.refreshToken,
      grant_type: "refresh_token",
    }).toString(),
    { headers: { "Content-Type": "application/x-www-form-urlencoded" }, timeout: 15_000 },
  );
  _token = {
    value: String(data.access_token),
    expiresAt: Date.now() + Number(data.expires_in ?? 3600) * 1000,
  };
  return _token.value;
}

async function gmailGet<T>(path: string, params?: Record<string, unknown>): Promise<T> {
  const token = await accessToken();
  const { data } = await axios.get<T>(`${GMAIL_BASE}${path}`, {
    headers: { Authorization: `Bearer ${token}` },
    params,
    timeout: 30_000,
  });
  return data;
}

async function gmailPost<T>(path: string, body: unknown): Promise<T> {
  const token = await accessToken();
  const { data } = await axios.post<T>(`${GMAIL_BASE}${path}`, body, {
    headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" },
    timeout: 30_000,
  });
  return data;
}

// ─── Tipos mínimos do payload do Gmail ───────────────────────────────────────

type GmailPart = {
  mimeType?: string;
  filename?: string;
  headers?: Array<{ name?: string; value?: string }>;
  body?: { data?: string; attachmentId?: string; size?: number };
  parts?: GmailPart[];
};

type GmailMessage = {
  id: string;
  threadId?: string;
  payload?: GmailPart;
};

function headerMap(payload: GmailPart | undefined): Record<string, string> {
  const map: Record<string, string> = {};
  for (const h of payload?.headers ?? []) {
    if (h.name) map[h.name.toLowerCase()] = h.value ?? "";
  }
  return map;
}

/** Percorre a árvore MIME e devolve o melhor corpo em texto. */
function extractBody(payload: GmailPart | undefined): string {
  let plain = "";
  let html = "";
  const walk = (p: GmailPart | undefined): void => {
    if (!p) return;
    if (p.mimeType === "text/plain" && p.body?.data && !plain) {
      plain = decodeBase64Url(p.body.data).toString("utf8");
    } else if (p.mimeType === "text/html" && p.body?.data && !html) {
      html = decodeBase64Url(p.body.data).toString("utf8");
    }
    for (const child of p.parts ?? []) walk(child);
  };
  walk(payload);
  if (plain) return plain;
  if (html) return htmlToText(html);
  return "";
}

type AttachmentRef = { attachmentId: string; mimeType: string; size: number };

function findAttachments(payload: GmailPart | undefined): AttachmentRef[] {
  const out: AttachmentRef[] = [];
  const walk = (p: GmailPart | undefined): void => {
    if (!p) return;
    const mime = (p.mimeType ?? "").toLowerCase();
    if (
      p.filename &&
      p.body?.attachmentId &&
      (mime.startsWith("image/") || mime === "application/pdf")
    ) {
      out.push({
        attachmentId: p.body.attachmentId,
        mimeType: mime,
        size: p.body.size ?? 0,
      });
    }
    for (const child of p.parts ?? []) walk(child);
  };
  walk(payload);
  return out;
}

// ─── Contexto de resposta por conversa ───────────────────────────────────────
// A fila coalesce emails em rajada num turno só; a resposta vai para a thread
// do email MAIS RECENTE daquele remetente.

type ReplyContext = {
  to: string;
  subject: string | null;
  threadId: string | null;
  messageIdHeader: string | null; // valor do header Message-ID (com <>)
  references: string | null;
  // ID do Gmail da mensagem original — no modo n8n, o nó Gmail → Reply usa
  // este id para responder na mesma thread.
  gmailMessageId: string | null;
  // NOSSA caixa em que o email chegou (multi-caixa). A resposta sai por ela —
  // o fluxo de envio do n8n roteia pelo campo "mailbox" do payload.
  mailbox: string;
};
const _replyContext = new Map<string, ReplyContext>();

/**
 * Persiste o email aceito (texto + contexto de resposta) em aria_pending_emails.
 * Se o processo reiniciar antes do turno completar, o boot reenfileira — o
 * cliente nunca fica sem resposta por causa de um deploy. Anexos não são
 * persistidos (payload compacto); num replay raro, o turno segue só com o texto.
 */
function persistPending(chatId: string, pushName: string | null, text: string, ctx: ReplyContext): void {
  if (!text) return; // email só-anexo: sem texto não há o que reenfileirar
  void savePendingEmail(chatId, { pushName, text, ctx: ctx as unknown as Record<string, unknown> }).catch(
    (err) => console.warn("[email] persistPending falhou:", err instanceof Error ? err.message : err),
  );
}

/** Reenfileira emails que ficaram pendentes num restart (boot). */
async function replayPendingEmails(): Promise<void> {
  let pending: Awaited<ReturnType<typeof loadPendingEmails>>;
  try {
    pending = await loadPendingEmails(config.email.maxAgeDays);
  } catch {
    return; // tabela ainda não migrada / banco fora — nada a reprocessar
  }
  for (const { chatId, record } of pending) {
    const ctx = record.ctx as unknown as ReplyContext;
    if (!ctx?.to) continue;
    _replyContext.set(chatId, ctx);
    console.log(`[email] reenfileirando email pendente de ${ctx.to} (restart)`);
    enqueueMessage(
      chatId,
      record.pushName,
      [{ type: "text", text: record.text }],
      processEmailTurn,
      config.reply.debounceMs,
    );
  }
}

// ─── Varredura da caixa ──────────────────────────────────────────────────────

async function sweep(): Promise<void> {
  let ids: Array<{ id: string }> = [];
  try {
    const res = await gmailGet<{ messages?: Array<{ id: string }> }>("/messages", {
      q: `in:inbox is:unread newer_than:${Math.max(1, config.email.maxAgeDays)}d`,
      maxResults: 10,
    });
    ids = res.messages ?? [];
  } catch (err) {
    console.warn("[email] falha ao listar caixa:", err instanceof Error ? err.message : err);
    return;
  }

  for (const { id } of ids) {
    try {
      await processInbound(id);
    } catch (err) {
      console.warn(`[email] falha ao processar ${id}:`, err instanceof Error ? err.message : err);
    }
  }
}

async function processInbound(gmailId: string): Promise<void> {
  // Dedup persistida (sobrevive a restart) — mesma tabela do WhatsApp.
  const fresh = await markMessageProcessed(`gmail:${gmailId}`).catch(() => true);
  if (!fresh) return;

  const msg = await gmailGet<GmailMessage>(`/messages/${gmailId}`, { format: "full" });
  const headers = headerMap(msg.payload);
  const fromAddr = extractAddress(headers["from"] ?? "");

  // Guardas: nunca responder automáticos, no-reply ou a própria caixa.
  if (!fromAddr || fromAddr === config.email.address) {
    await markAsRead(gmailId).catch(() => {});
    console.log(`[email] ignorado (ilegível/próprio): ${fromAddr ?? "?"}`);
    return;
  }
  const skipReason = isNoReplyAddress(fromAddr)
    ? "remetente no-reply/daemon"
    : isAutoGenerated(headers)
      ? "email automático (headers de lista/auto-resposta)"
      : null;
  if (skipReason) {
    await markAsRead(gmailId).catch(() => {});
    console.log(`[email] ignorado (automático/no-reply): ${fromAddr}`);
    // Registra no painel (aba Fora de escopo) — o operador vê tudo que foi
    // ignorado e pega eventual falso positivo. Custo zero de modelo.
    void logScopeBlock({
      chatId: emailChatId(fromAddr),
      channel: "email",
      sender: fromAddr,
      subject: headers["subject"] ?? null,
      layer: "structural",
      reason: skipReason,
      snippet: null,
    }).catch(() => {});
    return;
  }

  const rawBody = extractBody(msg.payload);
  const freshText = stripQuotedReply(rawBody);

  const blocks: AriaContentBlock[] = [];
  if (freshText) blocks.push({ type: "text", text: freshText });

  // Anexos de imagem/PDF → blocos multimodais (mesmo poder do WhatsApp).
  for (const att of findAttachments(msg.payload)) {
    if (att.size > MAX_ATTACHMENT_BYTES) continue;
    try {
      const data = await gmailGet<{ data?: string }>(
        `/messages/${gmailId}/attachments/${att.attachmentId}`,
      );
      if (!data.data) continue;
      const b64 = decodeBase64Url(data.data).toString("base64");
      if (att.mimeType === "application/pdf") {
        blocks.push({
          type: "document",
          source: { type: "base64", media_type: "application/pdf", data: b64 },
        });
      } else {
        const mediaType = normalizeImageMime(att.mimeType);
        if (mediaType) {
          blocks.push({ type: "image", source: { type: "base64", media_type: mediaType, data: b64 } });
        }
      }
    } catch (err) {
      console.warn("[email] anexo ignorado:", err instanceof Error ? err.message : err);
    }
  }

  if (blocks.length === 0) {
    await markAsRead(gmailId).catch(() => {});
    return;
  }

  const chatId = emailChatId(fromAddr);
  const displayName = extractDisplayName(headers["from"] ?? "");

  // Contexto da resposta: sempre a thread do email mais recente.
  const replyCtx: ReplyContext = {
    to: fromAddr,
    subject: headers["subject"] ?? null,
    threadId: msg.threadId ?? null,
    messageIdHeader: headers["message-id"] ?? null,
    references: headers["references"] ?? null,
    gmailMessageId: gmailId,
    mailbox: config.email.address, // modo direto vigia só a caixa principal
  };
  _replyContext.set(chatId, replyCtx);
  persistPending(chatId, displayName, freshText, replyCtx);

  // O assunto entra no log do painel (não no turno do agente — lá ele vai no
  // systemHint) para o operador acompanhar sem abrir o Gmail.
  const subjectPrefix = headers["subject"] ? `[${headers["subject"]}] ` : "";
  void logMessage({
    chatId,
    pushName: displayName,
    direction: "inbound",
    waMessageId: `gmail:${gmailId}`,
    content: subjectPrefix + (freshText || "[anexo]"),
    hasMedia: blocks.some((b) => b.type !== "text"),
    mediaType: blocks.some((b) => b.type === "document") ? "pdf" : blocks.some((b) => b.type === "image") ? "image" : null,
  });

  // Marca como lida ANTES do turno do agente — dedup já garante envio único,
  // e um erro no agente não pode reprocessar o email em loop.
  await markAsRead(gmailId).catch(() => {});

  enqueueMessage(chatId, displayName, blocks, processEmailTurn, config.reply.debounceMs);
}

function normalizeImageMime(
  mime: string,
): "image/jpeg" | "image/png" | "image/gif" | "image/webp" | null {
  if (mime.includes("png")) return "image/png";
  if (mime.includes("gif")) return "image/gif";
  if (mime.includes("webp")) return "image/webp";
  if (mime.includes("jpg") || mime.includes("jpeg")) return "image/jpeg";
  return null;
}

// ─── Entrada via n8n (POST /webhook/email) ───────────────────────────────────

/**
 * Processa um email encaminhado pelo n8n (Gmail Trigger → HTTP Request).
 * Mesmo pipeline do modo direto: guardas anti-loop, dedup, texto novo sem
 * citação, anexos opcionais em base64 — e o turno do agente na fila.
 * Quem marca como lido no Gmail é o próprio fluxo do n8n.
 */
export async function handleInboundEmail(payload: unknown): Promise<void> {
  const mail = normalizeInboundEmail(payload);
  if (!mail) {
    console.warn("[email] webhook n8n: payload sem remetente ou messageId — ignorado");
    return;
  }

  // Dedup persistida ANTES das guardas — o n8n pode reentregar em retry e um
  // skip registrado 2x sujaria o painel.
  const fresh = await markMessageProcessed(`gmail:${mail.messageId}`).catch(() => true);
  if (!fresh) return;

  // Própria caixa (qualquer uma das nossas): ignora sem registrar. Evita loop
  // caixa-a-caixa — ex.: notificação enviada por reservation@ chegando em
  // support@ via encaminhamento.
  if (OWN_ADDRESSES.includes(mail.from)) return;

  const skipReason = isNoReplyAddress(mail.from)
    ? "remetente no-reply/daemon"
    : isAutoGenerated({
          "auto-submitted": mail.autoSubmitted ?? "",
          precedence: mail.precedence ?? "",
          "list-id": mail.listId ?? "",
        })
      ? "email automático (headers de lista/auto-resposta)"
      : subjectLooksAutoReply(mail.subject)
        ? "assunto de auto-resposta/entrega"
        : null;
  if (skipReason) {
    console.log(`[email] ignorado (automático/no-reply): ${mail.from}`);
    void logScopeBlock({
      chatId: emailChatId(mail.from),
      channel: "email",
      sender: mail.from,
      subject: mail.subject,
      layer: "structural",
      reason: skipReason,
      snippet: null,
    }).catch(() => {});
    return;
  }

  // O corpo pode vir em text, html, na árvore MIME (payload do Gmail Trigger)
  // ou, em último caso, no snippet (preview curto). Extrai na melhor ordem.
  const rawBody =
    mail.text ||
    (mail.html ? htmlToText(mail.html) : "") ||
    (mail.payload ? extractBody(mail.payload as GmailPart) : "") ||
    mail.snippet ||
    "";
  const freshText = stripQuotedReply(rawBody);

  const blocks: AriaContentBlock[] = [];
  if (freshText) blocks.push({ type: "text", text: freshText });
  for (const att of mail.attachments) {
    if (Buffer.byteLength(att.data, "base64") > MAX_ATTACHMENT_BYTES) continue;
    if (att.mimeType === "application/pdf") {
      blocks.push({ type: "document", source: { type: "base64", media_type: "application/pdf", data: att.data } });
    } else {
      const mediaType = normalizeImageMime(att.mimeType);
      if (mediaType) blocks.push({ type: "image", source: { type: "base64", media_type: mediaType, data: att.data } });
    }
  }
  if (blocks.length === 0) return;

  const chatId = emailChatId(mail.from);
  const replyCtx: ReplyContext = {
    to: mail.from,
    subject: mail.subject,
    threadId: mail.threadId,
    messageIdHeader: null,
    references: null,
    gmailMessageId: mail.messageId,
    // Multi-caixa: campo "mailbox" do fluxo n8n → header To → caixa principal.
    mailbox: resolveMailbox(mail.mailbox, mail.to, OWN_ADDRESSES, config.email.address),
  };
  _replyContext.set(chatId, replyCtx);
  persistPending(chatId, mail.fromName, freshText, replyCtx);

  void logMessage({
    chatId,
    pushName: mail.fromName,
    direction: "inbound",
    waMessageId: `gmail:${mail.messageId}`,
    content: (mail.subject ? `[${mail.subject}] ` : "") + (freshText || "[anexo]"),
    hasMedia: blocks.some((b) => b.type !== "text"),
    mediaType: blocks.some((b) => b.type === "document") ? "pdf" : blocks.some((b) => b.type === "image") ? "image" : null,
  });

  enqueueMessage(chatId, mail.fromName, blocks, processEmailTurn, config.reply.debounceMs);
}

// ─── Turno do agente (mesmo motor do WhatsApp) ──────────────────────────────

async function processEmailTurn(
  chatId: string,
  pushName: string | null,
  blocks: AriaContentBlock[],
): Promise<void> {
  if (isHumanControlled(chatId)) {
    console.log(`[handoff] ${chatId} sob controle humano — Aria em silêncio`);
    // Humano assumiu — o email não fica pendente de replay.
    void clearPendingEmails(chatId).catch(() => {});
    return;
  }

  const ctx = _replyContext.get(chatId);
  if (!ctx) {
    console.warn(`[email] sem contexto de resposta para ${chatId} — turno descartado`);
    return;
  }

  const identity = emailIdentity(ctx.to);
  const userMsg = {
    role: "user" as const,
    content: blocks as unknown as Anthropic.MessageParam["content"],
  };

  const history = await getOrRestoreHistory(chatId);

  // Memória semântica: resumos de conversas anteriores relevantes (qualquer
  // canal — a chave de perfil unifica WhatsApp e email do mesmo cliente).
  let memoryHint = "";
  if (history.length === 0) {
    try {
      const profileKey = await resolveProfileKey(identity);
      const memories = await recallMemories(profileKey, textFromBlocks(blocks), 3);
      if (memories.length > 0) {
        memoryHint =
          `\n[Memórias de conversas anteriores relevantes para esta mensagem:\n` +
          memories.map((m) => `— ${m}`).join("\n") +
          `]`;
      }
    } catch {
      /* memória é best-effort */
    }
  }

  const systemHint = {
    role: "user" as const,
    content: [
      {
        type: "text" as const,
        text:
          `[Sistema: contato via EMAIL. Endereço do remetente: ${ctx.to}. ` +
          `Nome: ${pushName ?? "não informado"}. Assunto: ${ctx.subject ?? "(sem assunto)"}. ` +
          `Recebido na caixa: ${ctx.mailbox}. (Emails na caixa de notificações de reserva costumam ser estabelecimentos respondendo a um Pending Request — ver FLUXO 5.)]${memoryHint}`,
      },
    ],
  };

  // Bloqueio de escopo: newsletter/marketing/relatório automático de serviço
  // contratado → silêncio (registrado no painel). Camada determinística sempre;
  // classificador semântico só no primeiro contato.
  if (
    await isOutOfScope({
      channel: "email",
      chatId,
      sender: ctx.to,
      subject: ctx.subject,
      text: textFromBlocks(blocks),
      firstContact: history.length === 0,
    })
  ) {
    void clearPendingEmails(chatId).catch(() => {});
    return;
  }

  const seed = history.length === 0 ? [systemHint] : [];
  const { reply, updatedHistory } = await runAgent([...history, ...seed], userMsg, identity);

  setHistory(chatId, updatedHistory);

  const clean = sanitizeEmailReply(reply);
  if (!clean) {
    void clearPendingEmails(chatId).catch(() => {});
    return;
  }

  // Silêncio deliberado ou nota interna do agente — JAMAIS vai para o cliente.
  // Registra no painel (aba Fora de escopo) para o operador auditar a decisão.
  if (looksLikeInternalNote(clean)) {
    console.log(`[email] silêncio do agente para ${ctx.to} — nota interna suprimida`);
    void logScopeBlock({
      chatId,
      channel: "email",
      sender: ctx.to,
      subject: ctx.subject,
      layer: "semantic",
      reason: "Aria decidiu não responder (silêncio/nota interna suprimida)",
      snippet: clean.slice(0, 300),
    }).catch(() => {});
    void clearPendingEmails(chatId).catch(() => {});
    return;
  }

  const ok = await sendReply(ctx, clean);
  if (ok) {
    void logMessage({ chatId, pushName, direction: "outbound", content: clean });
  }
  // Turno completou (com ou sem entrega — o sendReply já re-tenta/loga).
  // Se o agente tivesse lançado antes daqui, o pendente ficaria para replay.
  void clearPendingEmails(chatId).catch(() => {});
}

// ─── Envio (mesma thread, headers de threading corretos) ────────────────────

async function sendReply(ctx: ReplyContext, body: string): Promise<boolean> {
  // Modo n8n: o envio é delegado ao fluxo do n8n (nó Gmail já autenticado).
  if (config.email.n8nSendWebhook) {
    try {
      await axios.post(
        config.email.n8nSendWebhook,
        {
          to: ctx.to,
          subject: replySubject(ctx.subject),
          text: body,
          html: renderEmailHtml(body, undefined, config.publicUrl),
          gmailMessageId: ctx.gmailMessageId, // nó Gmail → Reply usa este id (mesma thread)
          threadId: ctx.threadId,
          // Caixa que RECEBEU o email — o fluxo de envio do n8n roteia por este
          // campo (Switch) para o nó Gmail da credencial certa. Responder por
          // outra caixa quebraria a thread (o gmailMessageId é por caixa).
          mailbox: ctx.mailbox,
        },
        {
          headers: { "x-aria-secret": config.email.webhookSecret, "Content-Type": "application/json" },
          timeout: 30_000,
        },
      );
      return true;
    } catch (err) {
      console.error("[email] falha no envio via n8n:", err instanceof Error ? err.message : err);
      return false;
    }
  }

  const from = `${encodeMimeHeader(config.email.fromName)} <${config.email.address}>`;
  const references = [ctx.references, ctx.messageIdHeader].filter(Boolean).join(" ");

  // multipart/alternative: texto puro (fallback universal) + HTML na identidade
  // visual da TWK (src/emailTemplate.ts). Clientes escolhem a melhor versão.
  const boundary = "=_aria_" + Math.random().toString(36).slice(2);
  const b64 = (s: string) =>
    Buffer.from(s, "utf8").toString("base64").replace(/(.{76})/g, "$1\r\n");

  const headers = [
    `From: ${from}`,
    `To: ${ctx.to}`,
    `Subject: ${encodeMimeHeader(replySubject(ctx.subject))}`,
    ctx.messageIdHeader ? `In-Reply-To: ${ctx.messageIdHeader}` : null,
    references ? `References: ${references}` : null,
    "MIME-Version: 1.0",
    `Content-Type: multipart/alternative; boundary="${boundary}"`,
  ].filter(Boolean);

  const mime = [
    `--${boundary}`,
    'Content-Type: text/plain; charset="UTF-8"',
    "Content-Transfer-Encoding: base64",
    "",
    b64(body),
    `--${boundary}`,
    'Content-Type: text/html; charset="UTF-8"',
    "Content-Transfer-Encoding: base64",
    "",
    b64(renderEmailHtml(body, undefined, config.publicUrl)),
    `--${boundary}--`,
  ].join("\r\n");

  const raw = headers.join("\r\n") + "\r\n\r\n" + mime;
  const rawUrl = Buffer.from(raw, "utf8")
    .toString("base64")
    .replace(/\+/g, "-")
    .replace(/\//g, "_")
    .replace(/=+$/, "");

  try {
    await gmailPost("/messages/send", {
      raw: rawUrl,
      ...(ctx.threadId ? { threadId: ctx.threadId } : {}),
    });
    return true;
  } catch (err) {
    console.error("[email] falha no envio:", err instanceof Error ? err.message : err);
    return false;
  }
}

/**
 * Envio MANUAL pelo painel (operador humano) para um endereço atendido pelo
 * canal de email. Usa o contexto de resposta da última mensagem (mesma thread)
 * quando disponível; sem ele (restart), abre uma thread nova — o fluxo de
 * envio (n8n ou Gmail direto) cobre os dois casos. Retorna false se o canal
 * de email não estiver configurado.
 */
export async function sendOperatorEmail(address: string, body: string): Promise<boolean> {
  if (!config.email.enabled) return false;
  if (!config.email.n8nSendWebhook && !config.email.refreshToken) return false;
  const chatId = emailChatId(address);
  const ctx: ReplyContext = _replyContext.get(chatId) ?? {
    to: address,
    subject: "The World Keys",
    threadId: null,
    messageIdHeader: null,
    references: null,
    gmailMessageId: null,
    mailbox: config.email.address,
  };
  return sendReply(ctx, body);
}

async function markAsRead(gmailId: string): Promise<void> {
  await gmailPost(`/messages/${gmailId}/modify`, { removeLabelIds: ["UNREAD"] });
}

// ─── Ponto de entrada ────────────────────────────────────────────────────────

export function startEmailChannel(): void {
  if (!config.email.enabled) {
    console.log("[email] canal de email desativado (EMAIL_ENABLED=false)");
    return;
  }

  // ── Modo n8n: entrada via POST /webhook/email, saída via webhook do n8n ──
  if (config.email.n8nSendWebhook) {
    if (!config.email.webhookSecret) {
      console.warn(
        "[email] modo n8n requer EMAIL_WEBHOOK_SECRET (protege o endpoint de entrada) — canal não iniciado",
      );
      return;
    }
    console.log(
      `[email] canal ativo (modo n8n): ${config.email.address || "caixa do n8n"} · entrada em POST /webhook/email · saída via ${config.email.n8nSendWebhook.split("?")[0]}`,
    );
    // Replay de emails que um restart deixou sem resposta (após migrations).
    setTimeout(() => void replayPendingEmails(), 20_000);
    return; // sem polling — o Gmail Trigger do n8n empurra os emails
  }

  // ── Modo direto: Gmail API com credenciais próprias ──
  const missing = [
    !config.email.address && "EMAIL_ADDRESS",
    !config.email.clientId && "GMAIL_CLIENT_ID",
    !config.email.clientSecret && "GMAIL_CLIENT_SECRET",
    !config.email.refreshToken && "GMAIL_REFRESH_TOKEN",
  ].filter(Boolean);
  if (missing.length > 0) {
    console.warn(
      `[email] EMAIL_ENABLED=true porém faltam: ${missing.join(", ")} — configure o modo direto OU o modo n8n (N8N_EMAIL_SEND_WEBHOOK + EMAIL_WEBHOOK_SECRET)`,
    );
    return;
  }

  const intervalMs = Math.max(20, config.email.pollSeconds) * 1000;
  setTimeout(() => {
    void replayPendingEmails();
    void sweep();
    setInterval(() => void sweep(), intervalMs).unref();
  }, 15_000); // aguarda migrations/boot

  console.log(
    `[email] canal ativo (Gmail direto): ${config.email.address} · varredura a cada ${Math.max(20, config.email.pollSeconds)}s`,
  );
}
